// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors tracert.Params in internal/tools/tracert/tracert.go. */
export interface Params {
  host: string
  maxHops: number
  queries: number
  timeoutMs: number
  noNames: boolean
}

/** Mirrors tracert.Hop. timesMs and alsoSeen are never null from Go. */
export interface Hop {
  number: number
  ip: string
  hostname: string
  timesMs: number[]
  lost: number
  bestMs: number
  avgMs: number
  worstMs: number
  alsoSeen: string[]
  note: string
  final: boolean
}

interface Bound {
  main?: {
    App?: {
      StartTraceroute?: (params: Params) => Promise<string>
      GetAppInfo?: () => Promise<{
        version: string
        platform: string
        storeDir: string
        portable: boolean
      }>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Hops arrive as "hop" items on job:result. */
export async function startTrace(params: Params): Promise<string> {
  const fn = bound().main?.App?.StartTraceroute
  if (!fn) throw new Error('Traceroute is only available in the desktop app.')
  return fn(params)
}

/** "windows/amd64", "darwin/arm64", ... or null outside the desktop app. */
export async function platform(): Promise<string | null> {
  const fn = bound().main?.App?.GetAppInfo
  if (!fn) return null
  try {
    return (await fn()).platform
  } catch {
    return null
  }
}
