// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors totp.Status in internal/tools/totp/totp.go. */
export interface Status {
  hasVault: boolean
  unlocked: boolean
  accounts: number
  note: string
}

/** Mirrors totp.Account. It never carries the secret. */
export interface Account {
  id: string
  issuer: string
  label: string
  digits: number
  period: number
  algorithm: string
  addedAt: string
}

/** Mirrors totp.AccountList. */
export interface AccountList {
  accounts: Account[] | null
}

/** Mirrors totp.NewAccount. Either uri is filled in, or secret plus a name. */
export interface NewAccount {
  uri: string
  secret: string
  issuer: string
  label: string
}

/** Mirrors totp.Code. */
export interface Code {
  id: string
  issuer: string
  label: string
  code: string
  digits: number
  period: number
  expiresIn: number
}

/** Mirrors totp.CodeSet. */
export interface CodeSet {
  codes: Code[] | null
  atUnix: number
  note: string
}

/** Mirrors totp.ImportReport. */
export interface ImportReport {
  added: number
  skipped: number
  note: string
}

interface Bound {
  main?: {
    App?: {
      TOTPStatus?: () => Promise<Status>
      CreateTOTPVault?: (passphrase: string) => Promise<Status>
      UnlockTOTPVault?: (passphrase: string) => Promise<Status>
      LockTOTPVault?: () => Promise<Status>
      ListTOTPAccounts?: () => Promise<AccountList>
      TOTPCodes?: () => Promise<CodeSet>
      AddTOTPAccount?: (input: NewAccount) => Promise<Account>
      RemoveTOTPAccount?: (id: string) => Promise<Status>
      ExportTOTPVault?: () => Promise<string>
      ImportTOTPVault?: (fileJson: string, passphrase: string) => Promise<ImportReport>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

const NO_APP =
  'The code vault needs the desktop app. Codes and seeds never leave the machine, so there is nothing to show in a browser.'

/** Null outside the desktop app, so the page can render its own explanation. */
export async function totpStatus(): Promise<Status | null> {
  const fn = bound().main?.App?.TOTPStatus
  if (!fn) return null
  return fn()
}

export async function createVault(passphrase: string): Promise<Status> {
  const fn = bound().main?.App?.CreateTOTPVault
  if (!fn) throw new Error(NO_APP)
  return fn(passphrase)
}

export async function unlockVault(passphrase: string): Promise<Status> {
  const fn = bound().main?.App?.UnlockTOTPVault
  if (!fn) throw new Error(NO_APP)
  return fn(passphrase)
}

export async function lockVault(): Promise<Status> {
  const fn = bound().main?.App?.LockTOTPVault
  if (!fn) throw new Error(NO_APP)
  return fn()
}

export async function listAccounts(): Promise<AccountList> {
  const fn = bound().main?.App?.ListTOTPAccounts
  if (!fn) throw new Error(NO_APP)
  return fn()
}

export async function currentCodes(): Promise<CodeSet> {
  const fn = bound().main?.App?.TOTPCodes
  if (!fn) throw new Error(NO_APP)
  return fn()
}

export async function addAccount(input: NewAccount): Promise<Account> {
  const fn = bound().main?.App?.AddTOTPAccount
  if (!fn) throw new Error(NO_APP)
  return fn(input)
}

export async function removeAccount(id: string): Promise<Status> {
  const fn = bound().main?.App?.RemoveTOTPAccount
  if (!fn) throw new Error(NO_APP)
  return fn(id)
}

export async function exportVault(): Promise<string> {
  const fn = bound().main?.App?.ExportTOTPVault
  if (!fn) throw new Error(NO_APP)
  return fn()
}

export async function importVault(fileJson: string, passphrase: string): Promise<ImportReport> {
  const fn = bound().main?.App?.ImportTOTPVault
  if (!fn) throw new Error(NO_APP)
  return fn(fileJson, passphrase)
}
