// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors wol.WakeParams in internal/tools/wol/wol.go. */
export interface WakeParams {
  mac: string
  broadcast: string
  port: number
  password: string
}

/** Mirrors wol.Send in internal/tools/wol/wol.go. */
export interface Send {
  adapter: string
  from: string
  to: string
  port: number
  bytes: number
  error: string
}

/** Mirrors wol.WakeResult in internal/tools/wol/wol.go. */
export interface WakeResult {
  mac: string
  vendor: string
  sent: Send[] | null
  failed: Send[] | null
  packetHex: string
  note: string
}

/** Mirrors wol.Target in internal/tools/wol/targets.go. */
export interface Target {
  adapter: string
  from: string
  to: string
  port: number
}

/** Mirrors wol.TargetList in internal/tools/wol/wol.go. */
export interface TargetList {
  targets: Target[] | null
  note: string
}

/** Mirrors wol.Awake in internal/tools/wol/check.go. */
export interface Awake {
  ip: string
  alive: boolean
  via: string
  latencyMs: number
}

interface Bound {
  main?: {
    App?: {
      WakeDevice?: (params: WakeParams) => Promise<WakeResult>
      WakeTargets?: () => Promise<TargetList>
      CheckAwake?: (ip: string) => Promise<Awake>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

const NOT_IN_APP = 'Wake-on-LAN only works inside the CHIT desktop app.'

export async function wakeDevice(params: WakeParams): Promise<WakeResult> {
  const fn = bound().main?.App?.WakeDevice
  if (!fn) throw new Error(NOT_IN_APP)
  return fn(params)
}

export async function wakeTargets(): Promise<TargetList> {
  const fn = bound().main?.App?.WakeTargets
  if (!fn) throw new Error(NOT_IN_APP)
  return fn()
}

export async function checkAwake(ip: string): Promise<Awake> {
  const fn = bound().main?.App?.CheckAwake
  if (!fn) throw new Error(NOT_IN_APP)
  return fn(ip)
}
