// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors ouidb.Info in internal/ouidb/describe.go. */
export interface MacInfo {
  mac: string
  oui: string
  vendor: string
  found: boolean
  locallyAdministered: boolean
  randomized: boolean
  multicast: boolean
  broadcast: boolean
  note: string
}

/** Mirrors ouidb.Meta in internal/ouidb/ouidb.go. */
export interface MacDatabase {
  source: string
  fetched: string
  records: number
}

interface Bound {
  main?: {
    App?: {
      LookupMAC?: (mac: string) => Promise<MacInfo>
      MACDatabaseInfo?: () => Promise<MacDatabase>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function lookupMac(mac: string): Promise<MacInfo> {
  const fn = bound().main?.App?.LookupMAC
  if (!fn) throw new Error('The vendor database only works inside the CHIT desktop app.')
  return fn(mac)
}

/** Null when the app runs outside Wails (plain vite dev server). */
export async function macDatabase(): Promise<MacDatabase | null> {
  const fn = bound().main?.App?.MACDatabaseInfo
  if (!fn) return null
  return fn()
}
