// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors portlisten.Params in internal/tools/portlisten/portlisten.go. */
export interface ListenParams {
  port: number
  /** "tcp", "udp" or "both". */
  protocol: string
}

/** Mirrors portlisten.Hit. */
export interface Hit {
  time: string
  /** "tcp" or "udp", never "both". */
  protocol: string
  peer: string
  peerPort: number
  bytes: number
  preview: string
}

/** Mirrors filedrop.Address in internal/tools/filedrop/filedrop.go. */
export interface Address {
  ip: string
  adapter: string
  primary: boolean
}

interface Bound {
  main?: {
    App?: {
      StartPortListener?: (p: ListenParams) => Promise<string>
      // Already shipped and already bound by LAN File Drop. Owning no address
      // enumerator means writing no second one, not refusing to call the one
      // that is there. This tool does not touch internal/tools/filedrop or
      // app_filedrop.go.
      FileDropAddresses?: () => Promise<Address[] | null>
      FirewallHint?: (port: number, proto: string) => Promise<FirewallHint>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Arrivals come back as "hit" items on job:result. */
export async function startPortListener(p: ListenParams): Promise<string> {
  const fn = bound().main?.App?.StartPortListener
  if (!fn) throw new Error('Listening on a port is only available in the desktop app.')
  return fn(p)
}

/** Empty outside the desktop app: the page still renders, it just offers no address. */
export async function listenerAddresses(): Promise<Address[]> {
  const fn = bound().main?.App?.FileDropAddresses
  if (!fn) return []
  return (await fn()) ?? []
}

/** Mirrors firewall.Hint in internal/firewall/firewall.go. Every field is empty
 *  when nothing was detected, which the page renders as nothing at all. */
export interface FirewallHint {
  firewall: string
  message: string
  command: string
}

/**
 * Whether a firewall on this computer might be dropping the connections the
 * other machine is making. A dropped packet produces no error at either end, so
 * without this the page cannot tell "blocked" from "nobody has tried yet".
 * Empty outside the desktop app, and it must never throw: this is a hint beside
 * a working share, not the thing the user asked for.
 */
export async function firewallHint(port: number, proto: string): Promise<FirewallHint | null> {
  const fn = bound().main?.App?.FirewallHint
  if (!fn) return null
  try {
    return await fn(port, proto)
  } catch {
    return null
  }
}
