// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors diskscan.Params in internal/tools/diskscan/diskscan.go. */
export interface Params {
  path: string
}

/** Mirrors diskscan.Entry. One immediate child of the scanned folder. */
export interface Entry {
  name: string
  path: string
  dir: boolean
  bytes: number
  files: number
}

/** Mirrors diskscan.Largest, which arrives inside done.summary.largest. */
export interface Largest {
  path: string
  name: string
  bytes: number
}

interface Bound {
  main?: {
    App?: {
      StartDiskScan?: (params: Params) => Promise<string>
      PickScanFolder?: () => Promise<string>
      DiskScanHome?: () => Promise<string>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Results arrive as "entry" items on job:result. */
export async function startDiskScan(params: Params): Promise<string> {
  const fn = bound().main?.App?.StartDiskScan
  if (!fn) throw new Error('Measuring a drive is only available in the desktop app.')
  return fn(params)
}

/** Empty when the picker was cancelled. Null outside the desktop app. */
export async function pickScanFolder(): Promise<string | null> {
  const fn = bound().main?.App?.PickScanFolder
  if (!fn) return null
  return fn()
}

/** The folder offered on open. Null outside the desktop app. */
export async function diskScanHome(): Promise<string | null> {
  const fn = bound().main?.App?.DiskScanHome
  if (!fn) return null
  return fn()
}

/** Reads done.summary.largest defensively: summary is Record<string, unknown>. */
export function largestFrom(summary: Record<string, unknown> | undefined): Largest[] {
  const raw = summary?.largest
  if (!Array.isArray(raw)) return []
  return raw.flatMap((item) => {
    if (item === null || typeof item !== 'object') return []
    const row = item as Record<string, unknown>
    if (typeof row.path !== 'string' || typeof row.bytes !== 'number') return []
    return [
      {
        path: row.path,
        name: typeof row.name === 'string' ? row.name : row.path,
        bytes: row.bytes,
      },
    ]
  })
}
