// The files under frontend/wailsjs are generated by "wails build", so the shell
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as lib/useJob.ts).

export interface AppInfo {
  version: string
  platform: string
  storeDir: string
  portable: boolean
}

/** Mirrors selfupdate.Status in internal/selfupdate/selfupdate.go, which
 *  embeds update.Result, so the JSON is one flat object. */
export interface UpdateResult {
  current: string
  latest: string
  url: string
  newer: boolean
  published: string
  note: string
  canInstall: boolean
  installNote: string
  assetName: string
  assetSize: number
}

interface Bound {
  main?: {
    App?: {
      GetAppInfo?: () => Promise<AppInfo>
      CheckForUpdate?: () => Promise<UpdateResult>
      StartInstallUpdate?: () => Promise<string>
      RestartForUpdate?: () => Promise<boolean>
    }
  }
  store?: {
    Store?: {
      Get?: (namespace: string) => Promise<string>
      Set?: (namespace: string, jsonData: string) => Promise<void>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Null when the app runs outside Wails (plain vite dev server). */
export async function getAppInfo(): Promise<AppInfo | null> {
  const fn = bound().main?.App?.GetAppInfo
  if (!fn) return null
  return fn()
}

/** Asks GitHub whether a newer release exists. Only ever called from the button
 *  on the settings page, so CHIT never contacts GitHub on its own. */
export async function checkForUpdate(): Promise<UpdateResult> {
  const fn = bound().main?.App?.CheckForUpdate
  if (!fn) throw new Error('Checking for updates is only available in the desktop app.')
  return fn()
}

/** Resolves to the install job's id; progress arrives over the job events.
 *  The backend re-checks the release itself, so this takes nothing. */
export async function startInstallUpdate(): Promise<string> {
  const fn = bound().main?.App?.StartInstallUpdate
  if (!fn) throw new Error('Installing updates is only available in the desktop app.')
  return fn()
}

/** Starts the newly installed version and quits this one. */
export async function restartForUpdate(): Promise<boolean> {
  const fn = bound().main?.App?.RestartForUpdate
  if (!fn) throw new Error('Restarting is only available in the desktop app.')
  return fn()
}

/** Null when the document has never been saved, or outside Wails. */
export async function readDoc<T>(namespace: string): Promise<T | null> {
  const fn = bound().store?.Store?.Get
  if (!fn) return null
  const raw = await fn(namespace)
  if (!raw) return null
  return JSON.parse(raw) as T
}

export async function writeDoc(namespace: string, doc: object): Promise<void> {
  const fn = bound().store?.Store?.Set
  if (!fn) return
  await fn(namespace, JSON.stringify(doc))
}
