// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

export interface Params {
  host: string
  port: number
  timeoutMs: number
}

/** Mirrors rawprint.Result in internal/tools/rawprint/rawprint.go. */
export interface PrinterResult {
  host: string
  port: number
  address: string
  connected: boolean
  connectMs: number
  /** True only when the test page was actually sent. */
  printed: boolean
  bytesSent: number
  reply: string
  model: string
  statusCode: string
  display: string
  /** "true", "false" or "" when the printer did not say. */
  online: string
  /** "ok", "warn" or "error". */
  level: string
  headline: string
  advice: string
  checkedAt: string
}

interface Bound {
  main?: {
    App?: {
      QueryPrinter?: (p: Params) => Promise<PrinterResult>
      SendPrinterTestPage?: (p: Params) => Promise<PrinterResult>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Read-only. Cannot make paper move. */
export async function queryPrinter(p: Params): Promise<PrinterResult> {
  const fn = bound().main?.App?.QueryPrinter
  if (!fn) throw new Error('Printer testing is only available in the desktop app.')
  return fn(p)
}

/** Makes the printer produce a sheet of paper. */
export async function sendPrinterTestPage(p: Params): Promise<PrinterResult> {
  const fn = bound().main?.App?.SendPrinterTestPage
  if (!fn) throw new Error('Printer testing is only available in the desktop app.')
  return fn(p)
}
