// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors pubip.Info in internal/tools/pubip/pubip.go. */
export interface PublicIPInfo {
  ipv4: string
  ipv6: string
  reverseDns: string
  isp: string
  asn: string
  city: string
  region: string
  country: string
  countryName: string
  timezone: string
  latitude: number
  longitude: number
  source: string
  partial: boolean
  note: string
  checkedAt: string
}

interface Bound {
  main?: {
    App?: {
      PublicIP?: () => Promise<PublicIPInfo>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function publicIP(): Promise<PublicIPInfo> {
  const fn = bound().main?.App?.PublicIP
  if (!fn) throw new Error('Looking up the public IP only works inside the CHIT desktop app.')
  return fn()
}
