// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors pingmon.Params in internal/tools/pingmon/pingmon.go. */
export interface Params {
  targets: string[]
  intervalMs: number
  timeoutMs: number
  rounds: number
  tcpPort: number
  skipTcp: boolean
}

/** Mirrors pingmon.Sample in internal/tools/pingmon/pingmon.go. */
export interface Sample {
  round: number
  target: string
  ip: string
  ok: boolean
  latencyMs: number
  /** "icmp", "tcp" or "" when the ping was lost. */
  via: string
  /** Unix milliseconds. */
  at: number
  reason: string
}

interface Bound {
  main?: {
    App?: {
      StartPingMonitor?: (params: Params) => Promise<string>
      ScanDefaults?: () => Promise<{ range: string; adapter: string; ip: string; gateway: string }>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Samples arrive as "sample" items on job:result. */
export async function startPingMonitor(params: Params): Promise<string> {
  const fn = bound().main?.App?.StartPingMonitor
  if (!fn) throw new Error('Ping monitoring is only available in the desktop app.')
  return fn(params)
}

/** The gateway of the network this machine is on, or null when unavailable. */
export async function myGateway(): Promise<string | null> {
  const fn = bound().main?.App?.ScanDefaults
  if (!fn) return null
  try {
    const found = await fn()
    return found.gateway === '' ? null : found.gateway
  } catch {
    return null
  }
}
