// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors urlcheck.Params in internal/tools/urlcheck/urlcheck.go. */
export interface InspectParams {
  url: string
  timeoutMs: number
  skipAge: boolean
}

/** Mirrors urlcheck.Hop. */
export interface Hop {
  n: number
  url: string
  host: string
  method: string
  headRejected: boolean
  status: number
  location: string
  next: string
  tookMs: number
  error: string
}

/** Mirrors urlcheck.Finding. */
export interface Finding {
  id: string
  severity: string
  text: string
}

/** Mirrors urlcheck.Unwrap. */
export interface Unwrap {
  wrapper: string
  from: string
  to: string
}

/** Mirrors urlcheck.HostName. */
export interface HostName {
  raw: string
  decoded: string
  punycode: boolean
  registrable: string
  isIp: boolean
}

/** Mirrors urlcheck.Age. */
export interface Age {
  known: boolean
  registered: string
  days: number
  human: string
  note: string
}

/** Mirrors urlcheck.Report. Go slices arrive as null when empty, so read them with ?? []. */
export interface Report {
  input: string
  start: string
  final: string
  unwrapped: Unwrap[] | null
  hops: Hop[] | null
  startHost: HostName
  finalHost: HostName
  findings: Finding[] | null
  age: Age
  level: string
  headline: string
  stopped: string
  checkedAt: string
}

interface Bound {
  main?: {
    App?: {
      InspectLink?: (params: InspectParams) => Promise<Report>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function inspectLink(params: InspectParams): Promise<Report> {
  const fn = bound().main?.App?.InspectLink
  if (!fn) throw new Error('Inspecting a link only works inside the CHIT desktop app.')
  return fn(params)
}
