// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound method through the runtime global instead of importing
// a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors sysinfo.Disk in internal/tools/sysinfo/sysinfo.go. */
export interface Disk {
  mount: string
  fs: string
  total: number
  used: number
  free: number
  usedPct: number
}

/** Mirrors sysinfo.Report in internal/tools/sysinfo/sysinfo.go. */
export interface Report {
  hostname: string
  user: string
  os: string
  osName: string
  osVersion: string
  arch: string
  manufacturer: string
  model: string
  serial: string
  cpuModel: string
  cpuCores: number
  memoryTotal: number
  memoryFree: number
  uptimeS: number
  bootTime: string
  appVersion: string
  disks: Disk[] | null
  unsupported: string[] | null
}

interface Bound {
  main?: {
    App?: {
      SystemInfo?: () => Promise<Report>
    }
  }
}

export async function systemInfo(): Promise<Report> {
  const fn = (window as unknown as { go?: Bound }).go?.main?.App?.SystemInfo
  if (!fn) {
    throw new Error('System details are only available in the desktop app.')
  }
  return fn()
}
