// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

export interface Params {
  name: string
  type: string
  servers: string[]
  timeoutMs: number
}

/** Mirrors dnscmp.ServerOption. One tick box in the resolver list. */
export interface ServerOption {
  id: string
  label: string
  detail: string
}

/** Mirrors dnscmp.Answer in internal/tools/dnscmp/dnscmp.go. */
export interface DnsAnswer {
  server: string
  label: string
  values: string[]
  /** "ok", "empty" or "error". */
  status: string
  message: string
  queryMs: number
  inStep: boolean
}

/** Mirrors dnscmp.Comparison. */
export interface DnsComparison {
  name: string
  type: string
  answers: DnsAnswer[]
  majority: string[]
  majorityCount: number
  answered: number
  agree: boolean
  fastestLabel: string
  fastestMs: number
  /** "ok", "warn" or "error". */
  level: string
  headline: string
  advice: string
  checkedAt: string
}

interface Bound {
  main?: {
    App?: {
      CompareDNS?: (p: Params) => Promise<DnsComparison>
      DNSCompareServers?: () => Promise<ServerOption[]>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function compareDns(p: Params): Promise<DnsComparison> {
  const fn = bound().main?.App?.CompareDNS
  if (!fn) throw new Error('Comparing DNS resolvers is only available in the desktop app.')
  return fn(p)
}

const SYSTEM_ONLY: ServerOption[] = [
  { id: '', label: 'System resolver', detail: 'Whatever this computer is set to use' },
]

/** Falls back to the system resolver alone outside the desktop app. */
export async function dnsCompareServers(): Promise<ServerOption[]> {
  const fn = bound().main?.App?.DNSCompareServers
  if (!fn) return SYSTEM_ONLY
  try {
    return await fn()
  } catch {
    return SYSTEM_ONLY
  }
}
