// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

import type { Batch } from './journal'

/** Mirrors renamer.Params in internal/tools/renamer/renamer.go. */
export interface RenameParams {
  folder: string
  find: string
  replace: string
  useRegex: boolean
  case: '' | 'upper' | 'lower' | 'title'
  prefix: string
  suffix: string
  number: boolean
  start: number
  step: number
  padding: number
  keepExtension: boolean
}

/** Mirrors renamer.Row. */
export interface RenameRow {
  old: string
  new: string
  kind: 'file' | 'folder' | 'other'
  action: 'rename' | 'unchanged' | 'skipped' | 'blocked'
  reason: string
}

/** Mirrors renamer.Plan. Rows is never null: Go always returns a slice. */
export interface RenamePlan {
  folder: string
  fingerprint: string
  rows: RenameRow[]
  changed: number
  unchanged: number
  skipped: number
  blocked: number
  note: string
}

/** Mirrors renamer.ApplyItem. */
export interface ApplyItem {
  old: string
  new: string
  state: 'renamed' | 'failed' | 'skipped'
  reason: string
}

/** Mirrors renamer.ApplyResult. Items is never null. */
export interface ApplyResult {
  folder: string
  renamed: number
  failed: number
  skipped: number
  items: ApplyItem[]
  batch: Batch
  note: string
}

interface Bound {
  main?: {
    App?: {
      PickRenameFolder?: () => Promise<string>
      PreviewRename?: (params: RenameParams) => Promise<RenamePlan>
      ApplyRename?: (plan: RenamePlan) => Promise<ApplyResult>
      UndoRename?: (batch: Batch) => Promise<ApplyResult>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the chosen folder, or '' when the dialog was dismissed. */
export async function pickRenameFolder(): Promise<string> {
  const fn = bound().main?.App?.PickRenameFolder
  if (!fn)
    throw new Error(
      'Choosing a folder only works inside the CHIT desktop app. Type the full path instead.',
    )
  return fn()
}

export async function previewRename(params: RenameParams): Promise<RenamePlan> {
  const fn = bound().main?.App?.PreviewRename
  if (!fn) throw new Error('The bulk renamer only works inside the CHIT desktop app.')
  return fn(params)
}

export async function applyRename(plan: RenamePlan): Promise<ApplyResult> {
  const fn = bound().main?.App?.ApplyRename
  if (!fn) throw new Error('The bulk renamer only works inside the CHIT desktop app.')
  return fn(plan)
}

export async function undoRename(batch: Batch): Promise<ApplyResult> {
  const fn = bound().main?.App?.UndoRename
  if (!fn) throw new Error('The bulk renamer only works inside the CHIT desktop app.')
  return fn(batch)
}
