// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

export interface Params {
  target: string
  timeoutMs: number
}

/** Mirrors tlsprobe.Attempt in internal/tools/tlsprobe/tlsprobe.go. */
export interface TlsAttempt {
  version: string
  /** False only for SSL 3.0, which Go cannot speak. */
  testable: boolean
  accepted: boolean
  cipher: string
  alpn: string
  message: string
  handshakeMs: number
}

/** Mirrors tlsprobe.Report. */
export interface TlsReport {
  target: string
  host: string
  port: number
  ip: string
  attempts: TlsAttempt[]
  /** "ok", "warn" or "error". */
  level: string
  headline: string
  advice: string
  checkedAt: string
}

interface Bound {
  main?: {
    App?: {
      ProbeTLS?: (p: Params) => Promise<TlsReport>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function probeTls(p: Params): Promise<TlsReport> {
  const fn = bound().main?.App?.ProbeTLS
  if (!fn) throw new Error('TLS probing is only available in the desktop app.')
  return fn(p)
}
