// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors netstat.Entry in internal/tools/netstat/netstat.go. */
export interface Entry {
  /** "tcp", "tcp6", "udp" or "udp6". */
  protocol: string
  address: string
  port: number
  /** "everywhere", "local" or "one". */
  reach: string
  /** Zero when this operating system did not say. */
  pid: number
  /** Empty when the name is not visible to a normal user. */
  process: string
  service: string
  source: string
}

/** Mirrors netstat.Report. Both slices are Go slices, so both can be null. */
export interface Report {
  os: string
  entries: Entry[] | null
  processNames: boolean
  unsupported: string[] | null
  note: string
}

interface Bound {
  main?: {
    App?: {
      ListeningPorts?: () => Promise<Report>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function listeningPorts(): Promise<Report> {
  const fn = bound().main?.App?.ListeningPorts
  if (!fn) throw new Error('The listening ports list is only available in the desktop app.')
  return fn()
}
