// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors hibp.Result in internal/tools/hibp/hibp.go. */
export interface BreachResult {
  checked: boolean
  found: boolean
  count: number
  prefix: string
  compared: number
  level: string
  verdict: string
  checkedAt: string
}

interface Bound {
  main?: {
    App?: {
      CheckPasswordBreach?: (password: string) => Promise<BreachResult>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function checkPasswordBreach(password: string): Promise<BreachResult> {
  const fn = bound().main?.App?.CheckPasswordBreach
  if (!fn)
    throw new Error(
      'The breach check only works inside the CHIT desktop app. The strength rating above still works.',
    )
  return fn(password)
}
