// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors battery.Battery in internal/tools/battery/battery.go. */
export interface Battery {
  name: string
  /** "charging", "discharging", "full" or "unknown". */
  state: string
  /** 0 to 100, or -1 when unknown. */
  chargePercent: number
  designWh: number
  fullWh: number
  /** Not capped at 100: a battery can measure above its printed capacity. */
  healthPercent: number
  cycleCount: number
  technology: string
  manufacturer: string
  model: string
  serial: string
  verdict: string
  source: string
}

/** Mirrors battery.Report. Both slices are Go slices, so both can be null. */
export interface Report {
  os: string
  batteries: Battery[] | null
  onAc: boolean
  /** False when this operating system would not say, so the page can hide the line. */
  hasAc: boolean
  unsupported: string[] | null
  note: string
}

interface Bound {
  main?: {
    App?: {
      BatteryHealth?: () => Promise<Report>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function batteryHealth(): Promise<Report> {
  const fn = bound().main?.App?.BatteryHealth
  if (!fn) throw new Error('Battery details are only available in the desktop app.')
  return fn()
}
