// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors qrgen.Params in internal/tools/qrgen/qrgen.go. */
export interface QrParams {
  mode: string
  text: string
  ssid: string
  password: string
  security: string
  hidden: boolean
  ecLevel: string
}

/** Mirrors qrgen.Code in internal/tools/qrgen/qrgen.go. */
export interface QrCode {
  size: number
  version: number
  ecLevel: string
  mask: number
  /** size*size entries, row-major. Go always allocates it, so it is never null. */
  modules: boolean[]
  quiet: number
  payload: string
  payloadBytes: number
  capacity: number
}

interface Bound {
  main?: {
    App?: {
      GenerateQR?: (p: QrParams) => Promise<QrCode>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function generateQr(p: QrParams): Promise<QrCode> {
  const fn = bound().main?.App?.GenerateQR
  if (!fn) throw new Error('Making a QR code only works inside the CHIT desktop app.')
  return fn(p)
}
