// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

export interface Params {
  name: string
  types: string[]
  servers: string[]
  timeoutMs: number
}

/** Mirrors dnslook.Record in internal/tools/dnslook/dnslook.go. */
export interface DnsRecord {
  server: string
  type: string
  name: string
  value: string
  priority: number
  /** "ok", "empty" or "error". */
  status: string
  message: string
  queryMs: number
}

/** Mirrors dnslook.ServerOption. One tick box in the server list. */
export interface ServerOption {
  id: string
  label: string
  detail: string
}

interface Bound {
  main?: {
    App?: {
      StartDNSLookup?: (params: Params) => Promise<string>
      DNSServers?: () => Promise<ServerOption[]>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Records arrive as "record" items on job:result. */
export async function startLookup(params: Params): Promise<string> {
  const fn = bound().main?.App?.StartDNSLookup
  if (!fn) throw new Error('DNS lookups are only available in the desktop app.')
  return fn(params)
}

/** The system resolver plus this machine's servers plus the public ones.
 *  Falls back to just the system resolver outside the desktop app. */
export async function dnsServers(): Promise<ServerOption[]> {
  const fn = bound().main?.App?.DNSServers
  if (!fn)
    return [{ id: '', label: 'System resolver', detail: 'Whatever this computer is set to use' }]
  try {
    return await fn()
  } catch {
    return [{ id: '', label: 'System resolver', detail: 'Whatever this computer is set to use' }]
  }
}
