// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

export interface Params {
  timeoutMs: number
}

/** Mirrors triage.Rung in internal/tools/triage/triage.go. */
export interface Rung {
  id: string
  step: number
  name: string
  /** "ok", "warn", "fail" or "skipped". */
  status: string
  detail: string
  advice: string
  target: string
  ms: number
}

interface Bound {
  main?: {
    App?: {
      StartInternetTriage?: (p: Params) => Promise<string>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Rungs arrive as "rung" items on job:result. */
export async function startInternetTriage(p: Params): Promise<string> {
  const fn = bound().main?.App?.StartInternetTriage
  if (!fn) throw new Error('Internet triage is only available in the desktop app.')
  return fn(p)
}
