// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors diskbench.Params in internal/tools/diskbench/diskbench.go. */
export interface BenchParams {
  path: string
  sizeMb: number
}

/** Mirrors diskbench.Sample. */
export interface Sample {
  /** "write" or "read". */
  phase: string
  /** The running total for this phase. */
  bytes: number
  /** Elapsed seconds in this phase so far. */
  seconds: number
  /** The rate for this block group alone, in MB/s. */
  mbps: number
}

interface Bound {
  main?: {
    App?: {
      StartDiskSpeed?: (p: BenchParams) => Promise<string>
      PickBenchFolder?: () => Promise<string>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Samples arrive as "sample" items on job:result. */
export async function startDiskSpeed(p: BenchParams): Promise<string> {
  const fn = bound().main?.App?.StartDiskSpeed
  if (!fn) throw new Error('The disk speed test is only available in the desktop app.')
  return fn(p)
}

/** Empty when the picker was cancelled. Null outside the desktop app. */
export async function pickBenchFolder(): Promise<string | null> {
  const fn = bound().main?.App?.PickBenchFolder
  if (!fn) return null
  return fn()
}
