// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors filedrop.Address in internal/tools/filedrop/filedrop.go. */
export interface Address {
  ip: string
  adapter: string
  primary: boolean
}

/** Mirrors filedrop.Params. */
export interface Params {
  files: string[]
  port: number
  allowUpload: boolean
  receiveDir: string
}

/** Mirrors filedrop.Transfer. */
export interface Transfer {
  time: string
  /** "download" (they took a file) or "upload" (they sent one). */
  direction: string
  name: string
  bytes: number
  peer: string
  /** "ok" or "failed". */
  status: string
  message: string
}

/** Mirrors filedrop.Session. Empty when the job is not a running drop. */
export interface Session {
  token: string
  port: number
  url: string
  files: number
}

interface Bound {
  main?: {
    App?: {
      PickDropFiles?: () => Promise<string[] | null>
      PickDropFolder?: () => Promise<string>
      FileDropAddresses?: () => Promise<Address[] | null>
      StartFileDrop?: (params: Params) => Promise<string>
      FileDropSession?: (jobId: string) => Promise<Session>
      // Already shipped and already bound by the Wi-Fi QR tool. Owning no QR
      // package means writing no QR encoder, not refusing to call the one that
      // is there. This tool does not touch internal/tools/qrgen or app_qrgen.go.
      GenerateQR?: (p: QrParams) => Promise<QrCode>
    }
  }
}

/** Mirrors qrgen.Params in internal/tools/qrgen/qrgen.go. Only text mode is used here. */
export interface QrParams {
  mode: string
  text: string
  ssid: string
  password: string
  security: string
  hidden: boolean
  ecLevel: string
}

/** Mirrors qrgen.Code in internal/tools/qrgen/qrgen.go. */
export interface QrCode {
  size: number
  version: number
  ecLevel: string
  mask: number
  modules: boolean[]
  quiet: number
  payload: string
  payloadBytes: number
  capacity: number
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Transfers arrive as "transfer" items on job:result. */
export async function startFileDrop(params: Params): Promise<string> {
  const fn = bound().main?.App?.StartFileDrop
  if (!fn) throw new Error('Sharing files is only available in the desktop app.')
  return fn(params)
}

/** Empty when the picker was cancelled. Null outside the desktop app. */
export async function pickDropFiles(): Promise<string[] | null> {
  const fn = bound().main?.App?.PickDropFiles
  if (!fn) return null
  return fn()
}

export async function pickDropFolder(): Promise<string | null> {
  const fn = bound().main?.App?.PickDropFolder
  if (!fn) return null
  return fn()
}

export async function fileDropAddresses(): Promise<Address[]> {
  const fn = bound().main?.App?.FileDropAddresses
  if (!fn) return []
  return (await fn()) ?? []
}

/** The link a running drop is serving. Null outside the desktop app. */
export async function fileDropSession(jobId: string): Promise<Session | null> {
  const fn = bound().main?.App?.FileDropSession
  if (!fn) return null
  return fn(jobId)
}

/**
 * The QR module matrix for the sharing link. Null outside the desktop app: the
 * link is readable as text either way, so the code is a convenience rather than
 * the action the user asked for, and it must not throw.
 */
export async function generateQr(text: string): Promise<QrCode | null> {
  const fn = bound().main?.App?.GenerateQR
  if (!fn) return null
  try {
    return await fn({
      mode: 'text',
      text,
      ssid: '',
      password: '',
      security: '',
      hidden: false,
      ecLevel: '',
    })
  } catch {
    return null
  }
}
