// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

export interface Params {
  timeoutMs: number
}

/** Mirrors discover.Device in internal/tools/discover/discover.go. */
export interface Device {
  /** protocol + ip + service + name. The UI upserts by this. */
  key: string
  /** "mDNS" or "SSDP". */
  protocol: string
  ip: string
  name: string
  service: string
  host: string
  port: number
  details: string
  adapter: string
}

interface Bound {
  main?: {
    App?: {
      StartDeviceDiscovery?: (p: Params) => Promise<string>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Devices arrive as "device" items on job:result. */
export async function startDeviceDiscovery(p: Params): Promise<string> {
  const fn = bound().main?.App?.StartDeviceDiscovery
  if (!fn) throw new Error('Device discovery is only available in the desktop app.')
  return fn(p)
}
