// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors logview.Info in internal/tools/logview/logview.go. */
export interface Info {
  path: string
  name: string
  bytes: number
  modified: string
  crlf: boolean
}

/** Mirrors logview.Line. Number is 0 when the window did not start at byte 0. */
export interface Line {
  number: number
  offset: number
  text: string
  level: string
  truncated: boolean
}

/** Mirrors logview.Chunk. */
export interface Chunk {
  lines: Line[] | null
  start: number
  end: number
  bytes: number
  atStart: boolean
  atEnd: boolean
  shrank: boolean
}

/** Mirrors logview.ReadParams. Where is head, tail, at or before. */
export interface ReadParams {
  path: string
  where: string
  offset: number
  lines: number
}

/** Mirrors logview.SearchParams. */
export interface SearchParams {
  path: string
  query: string
  matchCase: boolean
}

/** Mirrors logview.Match. */
export interface Match {
  number: number
  offset: number
  text: string
  level: string
  col: number
  truncated: boolean
}

interface Bound {
  main?: {
    App?: {
      PickLogFile?: () => Promise<string>
      OpenLog?: (path: string) => Promise<Info>
      ReadLog?: (params: ReadParams) => Promise<Chunk>
      StartLogSearch?: (params: SearchParams) => Promise<string>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function openLog(path: string): Promise<Info> {
  const fn = bound().main?.App?.OpenLog
  if (!fn) throw new Error('Reading log files is only available in the desktop app.')
  return fn(path)
}

export async function readLog(params: ReadParams): Promise<Chunk> {
  const fn = bound().main?.App?.ReadLog
  if (!fn) throw new Error('Reading log files is only available in the desktop app.')
  return fn(params)
}

/** Resolves to the job id. Results arrive as "match" items on job:result. */
export async function startLogSearch(params: SearchParams): Promise<string> {
  const fn = bound().main?.App?.StartLogSearch
  if (!fn) throw new Error('Searching log files is only available in the desktop app.')
  return fn(params)
}

/** Empty when the picker was cancelled. Null outside the desktop app. */
export async function pickLogFile(): Promise<string | null> {
  const fn = bound().main?.App?.PickLogFile
  if (!fn) return null
  return fn()
}
