// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound method through the runtime global instead of importing
// a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors usbhist.Device in internal/tools/usbhist/usbhist.go. */
export interface Device {
  name: string
  manufacturer: string
  /** Four lowercase hex digits, or "" when the OS did not say. */
  vendorId: string
  productId: string
  serial: string
  /** storage, input, audio, video, network, printer, hub or other. */
  kind: string
  connected: boolean
  /** RFC3339, or "" when this OS does not record it. */
  firstSeen: string
  source: string
}

/** Mirrors usbhist.Report. */
export interface Report {
  os: string
  devices: Device[] | null
  /** True only where the OS records devices that are not connected now. */
  history: boolean
  unsupported: string[] | null
  note: string
}

interface Bound {
  main?: {
    App?: {
      USBDevices?: () => Promise<Report>
    }
  }
}

export async function usbDevices(): Promise<Report> {
  const fn = (window as unknown as { go?: Bound }).go?.main?.App?.USBDevices
  if (!fn) {
    throw new Error('USB device details are only available in the desktop app.')
  }
  return fn()
}
