// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound method through the runtime global instead of importing
// a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

export interface IPv4 {
  ip: string
  mask: string
  prefix: number
  cidr: string
  network: string
  broadcast: string
}

export interface IPv6 {
  ip: string
  prefix: number
  cidr: string
  scope: string
}

export interface Adapter {
  name: string
  friendlyName: string
  description: string
  index: number
  up: boolean
  mac: string
  mtu: number
  loopback: boolean
  virtual: boolean
  primary: boolean
  ipv4: IPv4[] | null
  ipv6: IPv6[] | null
  gateway: string
  dns: string[] | null
  /** "dhcp", "static", or "" when this OS does not report it. */
  dhcp: string
}

export interface AdapterReport {
  os: string
  hostname: string
  adapters: Adapter[] | null
  dns: string[] | null
  searchDomains: string[] | null
  /** Field ids this OS cannot report: "gateway", "dns", "adapterDns", "dhcp". */
  unsupported: string[] | null
}

interface Bound {
  main?: {
    App?: {
      ListAdapters?: () => Promise<AdapterReport>
    }
  }
}

export async function listAdapters(): Promise<AdapterReport> {
  const fn = (window as unknown as { go?: Bound }).go?.main?.App?.ListAdapters
  if (!fn) {
    throw new Error('Adapter details are only available in the desktop app.')
  }
  return fn()
}
