// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors wifi.Link in internal/tools/wifi/wifi.go. */
export interface Link {
  interface: string
  connected: boolean
  ssid: string
  bssid: string
  /** "2.4 GHz", "5 GHz", "6 GHz" or "". */
  band: string
  channel: number
  frequencyMhz: number
  widthMhz: number
  /** Zero when this operating system reports only a percentage. */
  signalDbm: number
  signalPercent: number
  rxMbps: number
  txMbps: number
  security: string
  reading: string
  source: string
}

/** Mirrors wifi.Report. Both slices are Go slices, so both can be null. */
export interface Report {
  os: string
  links: Link[] | null
  unsupported: string[] | null
  note: string
}

interface Bound {
  main?: {
    App?: {
      WiFiInfo?: () => Promise<Report>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function wifiInfo(): Promise<Report> {
  const fn = bound().main?.App?.WiFiInfo
  if (!fn) throw new Error('Wireless details are only available in the desktop app.')
  return fn()
}
