// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors portscan.Params in internal/tools/portscan/portscan.go. */
export interface Params {
  host: string
  /** The spec as typed: "443", "80,443", "1-1024", "80, 8000-8100". */
  ports: string
  timeoutMs: number
  workers: number
  grabBanners: boolean
}

/** Mirrors portscan.Result. One per port in the spec, emitted exactly once. */
export interface Result {
  port: number
  /** "open", "closed" or "filtered". */
  state: string
  service: string
  banner: string
  latencyMs: number
}

interface Bound {
  main?: { App?: { StartPortScan?: (params: Params) => Promise<string> } }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Results arrive as "port" items on job:result. */
export async function startPortScan(params: Params): Promise<string> {
  const fn = bound().main?.App?.StartPortScan
  if (!fn) throw new Error('Port scanning is only available in the desktop app.')
  return fn(params)
}
