// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors certdec.Name in internal/tools/certdec/certdec.go. */
export interface CertName {
  commonName: string
  organization: string[] | null
  organizationalUnit: string[] | null
  country: string[] | null
}

/** Mirrors certdec.Certificate in internal/tools/certdec/certdec.go. */
export interface DecodedCert {
  index: number
  subject: CertName
  issuer: CertName
  subjectLine: string
  issuerLine: string
  serialNumber: string
  notBefore: string
  notAfter: string
  daysRemaining: number
  expired: boolean
  notYetValid: boolean
  signatureAlgorithm: string
  weakSignature: boolean
  publicKeyAlgorithm: string
  publicKeyBits: number
  publicKeyLabel: string
  dnsNames: string[] | null
  ipAddresses: string[] | null
  emailAddresses: string[] | null
  uris: string[] | null
  keyUsage: string[] | null
  extendedKeyUsage: string[] | null
  isCa: boolean
  basicConstraintsValid: boolean
  maxPathLen: number
  pathLenText: string
  sha1Fingerprint: string
  sha256Fingerprint: string
  subjectKeyId: string
  authorityKeyId: string
  selfSigned: boolean
  version: number
  issuerInFile: number
  status: string
  statusLabel: string
  headline: string
  notes: string[] | null
  pem: string
}

/** Mirrors certdec.Result in internal/tools/certdec/certdec.go. */
export interface CertResult {
  certificates: DecodedCert[] | null
  format: string
  source: string
  chainNote: string
  inOrder: boolean
  suggestedOrder: number[] | null
  warnings: string[] | null
}

interface Bound {
  main?: {
    App?: {
      DecodeCertificateText?: (text: string) => Promise<CertResult>
      DecodeCertificateFile?: (path: string) => Promise<CertResult>
      PickCertFile?: () => Promise<string>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function decodeCertificateText(text: string): Promise<CertResult> {
  const fn = bound().main?.App?.DecodeCertificateText
  if (!fn) throw new Error('Reading a certificate only works inside the CHIT desktop app.')
  return fn(text)
}

export async function decodeCertificateFile(path: string): Promise<CertResult> {
  const fn = bound().main?.App?.DecodeCertificateFile
  if (!fn) throw new Error('Reading a certificate only works inside the CHIT desktop app.')
  return fn(path)
}

/** Resolves to '' when the user cancelled the dialog, which is not an error. */
export async function pickCertFile(): Promise<string> {
  const fn = bound().main?.App?.PickCertFile
  if (!fn) throw new Error('Choosing a file only works inside the CHIT desktop app.')
  return fn()
}
