// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors dupfind.Params in internal/tools/dupfind/dupfind.go. */
export interface Params {
  path: string
  minBytes: number
}

/** Mirrors dupfind.File. */
export interface DupFile {
  path: string
  name: string
  modified: string
}

/** Mirrors dupfind.Group. */
export interface Group {
  hash: string
  bytes: number
  count: number
  waste: number
  files: DupFile[] | null
}

interface Bound {
  main?: {
    App?: {
      StartDuplicateScan?: (params: Params) => Promise<string>
      PickDuplicateFolder?: () => Promise<string>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Results arrive as "group" items on job:result. */
export async function startDuplicateScan(params: Params): Promise<string> {
  const fn = bound().main?.App?.StartDuplicateScan
  if (!fn) throw new Error('Finding duplicates is only available in the desktop app.')
  return fn(params)
}

/** Empty when the picker was cancelled. Null outside the desktop app. */
export async function pickDuplicateFolder(): Promise<string | null> {
  const fn = bound().main?.App?.PickDuplicateFolder
  if (!fn) return null
  return fn()
}
