// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors hashfile.Params in internal/tools/hashfile/hashfile.go. */
export interface HashParams {
  path: string
}

/** Mirrors hashfile.Digests in internal/tools/hashfile/hashfile.go. */
export interface Digests {
  path: string
  name: string
  bytes: number
  md5: string
  sha1: string
  sha256: string
}

/** Mirrors hashfile.Verdict in internal/tools/hashfile/expected.go. */
export interface Verdict {
  state: 'none' | 'match' | 'mismatch' | 'unknown'
  algorithm: string
  expected: string
  actual: string
  message: string
}

interface Bound {
  main?: {
    App?: {
      PickHashFile?: () => Promise<string>
      StartFileHash?: (params: HashParams) => Promise<string>
      CompareHash?: (expected: string, digests: Digests) => Promise<Verdict>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the chosen path, or '' when the dialog was dismissed. */
export async function pickHashFile(): Promise<string> {
  const fn = bound().main?.App?.PickHashFile
  if (!fn) throw new Error('Choosing a file only works inside the CHIT desktop app. Type the full path instead.')
  return fn()
}

/** Resolves to the job id. One "digest" item arrives on job:result at the end. */
export async function startFileHash(params: HashParams): Promise<string> {
  const fn = bound().main?.App?.StartFileHash
  if (!fn) throw new Error('Hashing a file only works inside the CHIT desktop app.')
  return fn(params)
}

export async function compareHash(expected: string, digests: Digests): Promise<Verdict> {
  const fn = bound().main?.App?.CompareHash
  if (!fn) throw new Error('Hashing a file only works inside the CHIT desktop app.')
  return fn(expected, digests)
}
