// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors swlist.Program in internal/tools/swlist/swlist.go. */
export interface Program {
  name: string
  version: string
  publisher: string
  /** An RFC3339 date, or "" when this source records none. */
  installedOn: string
  /** Zero when this source records no size. */
  sizeBytes: number
  source: string
}

/** Mirrors swlist.Report. All three slices are Go slices, so all three can be null. */
export interface Report {
  os: string
  programs: Program[] | null
  sources: string[] | null
  unsupported: string[] | null
  note: string
}

interface Bound {
  main?: {
    App?: {
      InstalledSoftware?: () => Promise<Report>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function installedSoftware(): Promise<Report> {
  const fn = bound().main?.App?.InstalledSoftware
  if (!fn) throw new Error('The installed software list is only available in the desktop app.')
  return fn()
}
