// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** One address in the scanned range. Every address is reported, in use or not. */
export interface Host {
  ip: string
  /** "up" when something answered, "down" when the address stayed silent. */
  status: string
  /** "icmp", "tcp", "arp" or "" for an address that never answered. */
  respondedVia: string
  latencyMs: number
  hostname: string
  mac: string
  vendor: string
  openPorts: number[] | null
}

export interface ScanParams {
  range: string
  timeoutMs: number
  workers: number
  /** Empty means the built-in list of common ports. */
  ports: number[]
  skipTcp: boolean
  skipHostnames: boolean
}

export interface ScanDefaults {
  range: string
  adapter: string
  ip: string
  gateway: string
}

interface Bound {
  main?: {
    App?: {
      StartIPScan?: (params: ScanParams) => Promise<string>
      ScanDefaults?: () => Promise<ScanDefaults>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Results arrive as "host" items on job:result. */
export async function startScan(params: ScanParams): Promise<string> {
  const fn = bound().main?.App?.StartIPScan
  if (!fn) throw new Error('Scanning is only available in the desktop app.')
  return fn(params)
}

/** Null outside the desktop app or when this machine is not on a network. */
export async function scanDefaults(): Promise<ScanDefaults | null> {
  const fn = bound().main?.App?.ScanDefaults
  if (!fn) return null
  try {
    return await fn()
  } catch {
    return null
  }
}
