// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

export interface Params {
  servers: string[]
  timeoutMs: number
}

/** Mirrors ntpcheck.Server in internal/tools/ntpcheck/ntpcheck.go. */
export interface NtpServer {
  server: string
  address: string
  /** Positive when this computer is ahead of the server. */
  offsetMs: number
  delayMs: number
  stratum: number
  serverTime: string
  localTime: string
  /** "ok", "warn", "error" or "unreachable". */
  status: string
  message: string
}

/** Mirrors ntpcheck.Report. */
export interface NtpReport {
  servers: NtpServer[]
  /** "ok", "warn" or "error". */
  level: string
  headline: string
  advice: string
  checkedAt: string
}

interface Bound {
  main?: {
    App?: {
      CheckNTPTime?: (p: Params) => Promise<NtpReport>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function checkNtpTime(p: Params): Promise<NtpReport> {
  const fn = bound().main?.App?.CheckNTPTime
  if (!fn) throw new Error('The time check is only available in the desktop app.')
  return fn(p)
}
