// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors speedtest.Sample in internal/tools/speedtest/speedtest.go. */
export interface Sample {
  /** "latency", "download" or "upload". */
  phase: string
  elapsedMs: number
  bytes: number
  mbps: number
  avgMbps: number
  /** Set on latency samples only, 0 elsewhere. */
  latencyMs: number
  /** The last sample of a phase, carrying that phase's headline figure. */
  final: boolean
}

/** Mirrors speedtest.Params. Every zero value means "use the default". */
export interface SpeedParams {
  durationSec: number
  streams: number
  skipUpload: boolean
}

interface Bound {
  main?: {
    App?: {
      StartSpeedTest?: (params: SpeedParams) => Promise<string>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Results arrive as "sample" items on job:result. */
export async function startSpeedTest(params: SpeedParams): Promise<string> {
  const fn = bound().main?.App?.StartSpeedTest
  if (!fn) throw new Error('The speed test only works inside the CHIT desktop app.')
  return fn(params)
}
