// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

export interface Params {
  domain: string
  selector: string
  server: string
  timeoutMs: number
}

/** Mirrors maildns.MXHost. */
export interface MXHost {
  host: string
  preference: number
}

/** Mirrors maildns.SPFTerm. */
export interface SpfTerm {
  qualifier: string
  mechanism: string
  value: string
  costsLookup: boolean
  raw: string
}

/** Mirrors maildns.SPF. */
export interface Spf {
  found: boolean
  record: string
  count: number
  terms: SpfTerm[]
  all: string
  redirect: string
  lookups: number
  verdict: string
}

/** Mirrors maildns.DMARC. */
export interface Dmarc {
  found: boolean
  record: string
  count: number
  policy: string
  subdomain: string
  pct: number
  rua: string[]
  ruf: string[]
  verdict: string
}

/** Mirrors maildns.DKIMKey. */
export interface DkimKey {
  selector: string
  record: string
  hasKey: boolean
  keyType: string
}

/** Mirrors maildns.Finding. */
export interface Finding {
  /** "ok", "warn" or "error". */
  level: string
  /** "MX", "SPF", "DKIM" or "DMARC". */
  area: string
  title: string
  detail: string
}

/** Mirrors maildns.Report. */
export interface MailReport {
  domain: string
  server: string
  mx: MXHost[]
  nullMx: boolean
  spf: Spf
  dmarc: Dmarc
  dkim: DkimKey[]
  selectorsTried: string[]
  findings: Finding[]
  level: string
  headline: string
  checkedAt: string
}

interface Bound {
  main?: {
    App?: {
      CheckEmailDNS?: (p: Params) => Promise<MailReport>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function checkEmailDns(p: Params): Promise<MailReport> {
  const fn = bound().main?.App?.CheckEmailDNS
  if (!fn) throw new Error('The email DNS check is only available in the desktop app.')
  return fn(p)
}
