import type { ComponentType } from 'react'

export type ToolCategory =
  | 'network'
  | 'diagnostics'
  | 'remote'
  | 'utilities'
  | 'helpdesk'
  | 'security'
  | 'files'
  | 'system'

export interface ToolDef {
  /** Stable kebab-case id, matching the folder under src/tools/. */
  id: string
  name: string
  category: ToolCategory
  /** One line, shown on the home cards and in the command palette. */
  description: string
  /** Extra words a tech might search for. */
  keywords: string[]
  /** lucide-react icon name, e.g. 'Radar'. */
  icon: string
  element: () => Promise<{ default: ComponentType }>
  status?: 'stable' | 'beta' | 'partial'
}

/**
 * Every tool in the app. Adding a tool is one entry here plus one folder under
 * src/tools/<id>/. Keep entries alphabetical by id and one object each so two
 * people adding tools at the same time do not collide.
 *
 * {
 *   id: 'ip-range-scanner',
 *   name: 'IP Range Scanner',
 *   category: 'network',
 *   description: 'Ping-sweep a range and see which addresses are in use.',
 *   keywords: ['sweep', 'ping', 'subnet', 'discovery'],
 *   icon: 'Radar',
 *   element: () => import('./ip-range-scanner'),
 *   status: 'stable',
 * },
 */
export const TOOLS: ToolDef[] = [
  {
    id: 'adapter-info',
    name: 'Network Adapter Info',
    category: 'network',
    description: "This machine's adapters: IP, subnet, gateway, DNS, DHCP and MAC.",
    keywords: ['ipconfig', 'ifconfig', 'nic', 'interface', 'gateway', 'dns', 'dhcp', 'mac', 'mtu'],
    icon: 'Network',
    element: () => import('./adapter-info'),
    status: 'stable',
  },
  {
    id: 'battery-health',
    name: 'Battery Health',
    category: 'system',
    description: "How much of its original charge this laptop's battery still holds, and whether it is worth replacing.",
    keywords: ['battery', 'health', 'wear', 'cycle count', 'capacity', 'powercfg', 'batteryreport', 'laptop', 'charge', 'coconutbattery', 'replace battery', 'not holding charge', 'design capacity'],
    icon: 'Battery',
    element: () => import('./battery-health'),
    status: 'partial',
  },
  {
    id: 'breach-checker',
    name: 'Password Strength / Breach Checker',
    category: 'security',
    description: 'Rate a password and check it against known breaches without ever sending the password.',
    keywords: ['password', 'strength', 'entropy', 'breach', 'pwned', 'haveibeenpwned', 'hibp', 'leaked', 'compromised', 'k-anonymity', 'reused'],
    icon: 'ShieldAlert',
    element: () => import('./breach-checker'),
    status: 'stable',
  },
  {
    id: 'bulk-renamer',
    name: 'Bulk File Renamer',
    category: 'files',
    description: 'Rename every file in one folder by a rule, with a full before-and-after preview and an undo.',
    keywords: ['rename', 'batch rename', 'bulk', 'find and replace', 'numbering', 'prefix', 'suffix', 'file names', 'tidy up', 'ren'],
    icon: 'PenLine',
    element: () => import('./bulk-renamer'),
    status: 'stable',
  },
  {
    id: 'cert-decoder',
    name: 'Certificate Decoder',
    category: 'security',
    description: 'Paste or open a certificate and read its subject, issuer, names, expiry and chain.',
    keywords: ['certificate', 'cert', 'ssl', 'tls', 'x509', 'pem', 'cer', 'crt', 'der', 'openssl', 'expiry', 'san', 'chain', 'fingerprint', 'thumbprint'],
    icon: 'FileBadge',
    element: () => import('./cert-decoder'),
    status: 'stable',
  },
  {
    id: 'cert-generator',
    name: 'Certificate & CSR Generator',
    category: 'security',
    description: 'Make a self-signed certificate or a signing request for a device, with no openssl commands.',
    keywords: ['certificate', 'csr', 'self signed', 'openssl', 'x509', 'pem', 'private key', 'san', 'nas', 'idrac', 'ilo', 'switch gui', 'https warning', 'sign request', 'ecdsa', 'rsa'],
    icon: 'FileKey',
    element: () => import('./cert-generator'),
    status: 'stable',
  },
  {
    id: 'cron-explainer',
    name: 'Cron Explainer',
    category: 'utilities',
    description: 'Read a cron schedule in plain English and see the next five times it will run.',
    keywords: ['cron', 'crontab', 'schedule', 'scheduled job', 'backup job', 'nas', 'synology', 'qnap', 'five stars', 'asterisk', 'next run', 'timer', 'anacron'],
    icon: 'CalendarClock',
    element: () => import('./cron-explainer'),
    status: 'stable',
  },
  {
    id: 'csv-json-viewer',
    name: 'CSV / JSON Viewer and Converter',
    category: 'files',
    description: 'Open a CSV or JSON export, read it as a sortable table, and convert between the two.',
    keywords: ['csv', 'json', 'convert', 'export', 'spreadsheet', 'delimiter', 'tsv', 'table', 'viewer', 'excel'],
    icon: 'Table2',
    element: () => import('./csv-json-viewer'),
    status: 'stable',
  },
  {
    id: 'device-discovery',
    name: 'Device Discovery',
    category: 'network',
    description: 'Listen for printers, TVs, NAS boxes and casting devices announcing themselves on the network.',
    keywords: ['mdns', 'bonjour', 'ssdp', 'upnp', 'avahi', 'discovery', 'printer', 'chromecast', 'airplay', 'nas', 'zeroconf', 'multicast'],
    icon: 'RadioTower',
    element: () => import('./device-discovery'),
    status: 'stable',
  },
  {
    id: 'device-inventory',
    name: 'Saved Device Inventory',
    category: 'remote',
    description: 'Keep a list of the devices at each site, fed by a scan or by hand.',
    keywords: ['inventory', 'devices', 'asset', 'cmdb', 'static ip', 'site', 'printer', 'switch', 'what did we set', 'kit list', 'import scan'],
    icon: 'Boxes',
    element: () => import('./device-inventory'),
    status: 'stable',
  },
  {
    id: 'disk-speed',
    name: 'Disk Speed Test',
    category: 'system',
    description: 'Measure how fast a drive or a network share reads and writes, with a plain reading of the result.',
    keywords: ['disk speed', 'benchmark', 'crystaldiskmark', 'read write', 'ssd', 'hdd', 'nvme', 'usb stick', 'slow computer', 'dd', 'throughput', 'network share', 'failing drive'],
    icon: 'HardDrive',
    element: () => import('./disk-speed'),
    status: 'stable',
  },
  {
    id: 'disk-visualizer',
    name: 'Disk Space Visualizer',
    category: 'system',
    description: 'See what is actually filling a drive, folder by folder, and drill into the biggest one.',
    keywords: ['disk space', 'c drive full', 'treemap', 'windirstat', 'ncdu', 'du', 'folder size', 'what is using', 'storage', 'cleanup', 'biggest files', 'free up space'],
    icon: 'PieChart',
    element: () => import('./disk-visualizer'),
    status: 'stable',
  },
  {
    id: 'dns-compare',
    name: 'DNS Resolver Comparer',
    category: 'diagnostics',
    description: 'Ask several DNS servers the same question at once and see who disagrees.',
    keywords: ['dns', 'propagation', 'resolver', 'nslookup', 'dig', 'cache', 'stale', 'cutover', 'domain controller', 'ttl'],
    icon: 'GitCompare',
    element: () => import('./dns-compare'),
    status: 'stable',
  },
  {
    id: 'dns-lookup',
    name: 'DNS Lookup',
    category: 'diagnostics',
    description: 'Look up A, AAAA, CNAME, MX, TXT, NS, SRV and PTR records against one or more DNS servers.',
    keywords: ['dns', 'nslookup', 'dig', 'a record', 'mx', 'txt', 'cname', 'ptr', 'reverse lookup', 'resolver', 'spf', 'nameserver'],
    icon: 'Globe',
    element: () => import('./dns-lookup'),
    status: 'stable',
  },
  {
    id: 'duplicate-finder',
    name: 'Duplicate File Finder',
    category: 'files',
    description: 'Find files whose contents are identical, so you can see what is worth deleting.',
    keywords: ['duplicate', 'duplicates', 'same file', 'copies', 'reclaim space', 'disk full', 'hash', 'sha256', 'photos', 'backup', 'wasted space', 'dedupe'],
    icon: 'CopyCheck',
    element: () => import('./duplicate-finder'),
    status: 'stable',
  },
  {
    id: 'email-dns',
    name: 'Email DNS Checker',
    category: 'diagnostics',
    description: "Check a domain's MX, SPF, DKIM and DMARC records and say in plain English what they allow.",
    keywords: ['spf', 'dkim', 'dmarc', 'mx', 'email', 'mail', 'spam', 'spoof', 'junk', 'deliverability', 'mxtoolbox'],
    icon: 'MailCheck',
    element: () => import('./email-dns'),
    status: 'stable',
  },
  {
    id: 'file-hash',
    name: 'File Hash Checker',
    category: 'files',
    description: 'Get the MD5, SHA-1 and SHA-256 of a file and check it against the value the vendor published.',
    keywords: ['hash', 'checksum', 'md5', 'sha1', 'sha256', 'iso', 'verify', 'integrity', 'sha256sum', 'certutil', 'get-filehash', 'download'],
    icon: 'FileCheck',
    element: () => import('./file-hash'),
    status: 'stable',
  },
  {
    id: 'installed-software',
    name: 'Installed Software List',
    category: 'system',
    description: 'List what is installed on this machine, with versions, and export it.',
    keywords: ['installed', 'programs', 'add remove programs', 'appwiz', 'software audit', 'version', 'publisher', 'inventory', 'winget', 'apt', 'dpkg', 'rpm', 'pacman', 'applications', 'intake'],
    icon: 'Package',
    element: () => import('./installed-software'),
    status: 'partial',
  },
  {
    id: 'internet-triage',
    name: 'Internet Triage',
    category: 'diagnostics',
    description: 'Run the whole "is the internet down?" checklist in order and show exactly where it breaks.',
    keywords: ['internet', 'no connection', 'offline', 'gateway', 'dns', 'captive portal', 'wifi login', 'triage', 'ladder', 'troubleshoot'],
    icon: 'Stethoscope',
    element: () => import('./internet-triage'),
    status: 'stable',
  },
  {
    id: 'ip-range-scanner',
    name: 'IP Range Scanner',
    category: 'network',
    description: 'Sweep a range and see at a glance which addresses are in use and which are free.',
    keywords: ['sweep', 'ping', 'subnet', 'discovery', 'free ip', 'static ip', 'arp', 'scan'],
    icon: 'Radar',
    element: () => import('./ip-range-scanner'),
    status: 'stable',
  },
  {
    id: 'keyboard-tester',
    name: 'Keyboard and Input Tester',
    category: 'system',
    description: 'Press every key and click every button to prove what works and what does not.',
    keywords: ['keyboard', 'key test', 'stuck key', 'dead key', 'mouse test', 'double click', 'scroll wheel', 'ghosting', 'keycode', 'sticky keys', 'spill', 'laptop keyboard', 'input'],
    icon: 'Keyboard',
    element: () => import('./keyboard-tester'),
    status: 'partial',
  },
  {
    id: 'label-maker',
    name: 'Label Maker',
    category: 'helpdesk',
    description: 'Make printable equipment labels with an asset tag, a hostname, an address and a QR code.',
    keywords: ['label', 'asset tag', 'sticker', 'print', 'dymo', 'brother', 'avery', 'qr code', 'hostname', 'inventory tag', 'equipment'],
    icon: 'Tags',
    element: () => import('./label-maker'),
    status: 'stable',
  },
  {
    id: 'lan-file-drop',
    name: 'LAN File Drop',
    category: 'remote',
    description: 'Hand a file to another machine on the same network through its web browser, with no USB stick.',
    keywords: ['file transfer', 'send file', 'share', 'usb stick', 'driver', 'installer', 'http', 'download', 'upload', 'airdrop', 'network share', 'qr code', 'phone'],
    icon: 'Send',
    element: () => import('./lan-file-drop'),
    status: 'stable',
  },
  {
    id: 'lan-throughput',
    name: 'LAN Throughput Test',
    category: 'network',
    description: 'Measure the real transfer speed between this machine and another one on the same network.',
    keywords: ['lan speed', 'throughput', 'iperf', 'gigabit', '100 mbps', 'duplex', 'cable', 'switch port', 'wifi speed', 'file copy slow', 'bandwidth', 'network speed'],
    icon: 'ArrowDownUp',
    element: () => import('./lan-throughput'),
    status: 'stable',
  },
  {
    id: 'listening-ports',
    name: 'Listening Ports',
    category: 'system',
    description: 'See what is listening on this machine, on which address and port, and which program owns it.',
    keywords: ['netstat', 'ss', 'lsof', 'port in use', 'address already in use', 'listening', 'bound', 'what is on 8080', 'open ports', 'local ports', 'process', 'pid'],
    icon: 'Plug',
    element: () => import('./listening-ports'),
    status: 'partial',
  },
  {
    id: 'log-viewer',
    name: 'Log File Viewer',
    category: 'files',
    description: 'Open a huge log file instantly, jump to the end, search it and watch new lines arrive.',
    keywords: ['log', 'logfile', 'tail', 'follow', 'notepad', 'large file', 'search', 'grep', 'error', 'event log', 'setupact', 'catalina', 'syslog', 'trace'],
    icon: 'ScrollText',
    element: () => import('./log-viewer'),
    status: 'stable',
  },
  {
    id: 'mac-lookup',
    name: 'MAC / OUI Vendor Lookup',
    category: 'network',
    description: 'Paste a MAC address and find out who made the device.',
    keywords: ['mac', 'oui', 'vendor', 'manufacturer', 'hardware address', 'randomized'],
    icon: 'Fingerprint',
    element: () => import('./mac-lookup'),
    status: 'stable',
  },
  {
    id: 'ntp-check',
    name: 'NTP Time Check',
    category: 'diagnostics',
    description: "Compare this computer's clock against a time server and say whether the difference will break logins.",
    keywords: ['ntp', 'time', 'clock', 'skew', 'offset', 'kerberos', 'w32tm', 'sntp', 'drift', 'domain login'],
    icon: 'Clock',
    element: () => import('./ntp-check'),
    status: 'stable',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    category: 'utilities',
    description: 'Generate strong passwords or passphrases, with the exact strength in bits.',
    keywords: ['password', 'passphrase', 'random', 'strong password', 'generator', 'credentials', 'new user', 'wifi password', 'entropy', 'diceware'],
    icon: 'KeyRound',
    element: () => import('./password-generator'),
    status: 'stable',
  },
  {
    id: 'phishing-inspector',
    name: 'Phishing Link Inspector',
    category: 'security',
    description: 'Paste a suspicious link and see where it really ends up before anyone clicks it.',
    keywords: ['phishing', 'url', 'redirect', 'safelinks', 'shortener', 'punycode', 'homograph', 'suspicious link', 'is this legit', 'bit.ly', 'proofpoint', 'unwrap'],
    icon: 'Link2Off',
    element: () => import('./phishing-inspector'),
    status: 'stable',
  },
  {
    id: 'phonetic-alphabet',
    name: 'Phonetic Alphabet Converter',
    category: 'helpdesk',
    description: 'Turn a serial, licence key or password into a NATO readout you can say down the phone.',
    keywords: ['nato', 'icao', 'alfa bravo charlie', 'spell', 'serial number', 'licence key', 'product key', 'read out', 'phone', 'phonetic'],
    icon: 'Speech',
    element: () => import('./phonetic-alphabet'),
    status: 'stable',
  },
  {
    id: 'ping-monitor',
    name: 'Ping Monitor',
    category: 'diagnostics',
    description: 'Ping one or more hosts continuously with a live latency graph and a packet-loss count.',
    keywords: ['ping', 'latency', 'packet loss', 'flapping', 'continuous', 'icmp', 'jitter', 'drops', 'link', 'rtt'],
    icon: 'Activity',
    element: () => import('./ping-monitor'),
    status: 'stable',
  },
  {
    id: 'port-listener',
    name: 'Port Listener',
    category: 'diagnostics',
    description: 'Open a port on this machine so a test from the other side proves the path through the firewall.',
    keywords: ['firewall', 'listener', 'netcat', 'nc', 'open port', 'test-netconnection', 'telnet', 'inbound', 'nat', 'port forward', 'acl', 'udp', 'tcp', 'listen'],
    icon: 'Ear',
    element: () => import('./port-listener'),
    status: 'stable',
  },
  {
    id: 'port-scanner',
    name: 'Port Scanner',
    category: 'diagnostics',
    description: 'Check which TCP ports answer on a host, so you know whether to blame the firewall.',
    keywords: ['tcp', 'port', 'open port', 'firewall', 'rdp', 'ssh', 'smb', 'printer', 'listening', 'service', 'nmap'],
    icon: 'DoorOpen',
    element: () => import('./port-scanner'),
    status: 'stable',
  },
  {
    id: 'printer-test',
    name: 'Raw Printer Test',
    category: 'diagnostics',
    description: "Send a plain text page straight to a network printer's port 9100, with no driver installed.",
    keywords: ['printer', 'jetdirect', '9100', 'raw', 'pjl', 'test page', 'print queue', 'driver', 'spooler'],
    icon: 'Printer',
    element: () => import('./printer-test'),
    status: 'stable',
  },
  {
    id: 'public-ip-info',
    name: 'Public IP & Connection Info',
    category: 'diagnostics',
    description: "Show this site's public IP, ISP and rough location.",
    keywords: ['wan', 'external ip', 'whatsmyip', 'isp', 'asn', 'geolocation', 'public address', 'nat'],
    icon: 'Earth',
    element: () => import('./public-ip-info'),
    status: 'stable',
  },
  {
    id: 'reference-cards',
    name: 'IT Reference Cards',
    category: 'helpdesk',
    description: 'The lookups every tech googles: cable pinouts, port numbers, status codes, Wi-Fi channels and more.',
    keywords: ['reference', 'cheat sheet', 'pinout', 'rj45', '568a', '568b', 'patch cable', 'crossover', 'port numbers', 'well known ports', 'http status', '404', '502', 'wifi channels', 'dfs', 'subnet table', 'cidr table', 'beep codes', 'post beeps', 'sla', 'uptime', 'nines', 'downtime'],
    icon: 'BookOpen',
    element: () => import('./reference-cards'),
    status: 'stable',
  },
  {
    id: 'screen-ruler',
    name: 'Screen Ruler and Color Picker',
    category: 'utilities',
    description: "Measure in pixels, read this display's real resolution and scaling, and pick colours out of an image.",
    keywords: ['ruler', 'measure', 'pixels', 'colour picker', 'color picker', 'eyedropper', 'hex', 'rgb', 'hsl', 'dpi', 'scaling', 'resolution', 'display', 'contrast', 'blurry text'],
    icon: 'Ruler',
    element: () => import('./screen-ruler'),
    status: 'partial',
  },
  {
    id: 'site-checklist',
    name: 'Site Checklist Runner',
    category: 'helpdesk',
    description: 'Work through a checklist on site and export the finished run as proof it was done.',
    keywords: ['checklist', 'runbook', 'new pc', 'onboarding', 'decommission', 'office move', 'handover', 'sign off', 'proof of work', 'procedure', 'sop'],
    icon: 'ListChecks',
    element: () => import('./site-checklist'),
    status: 'stable',
  },
  {
    id: 'snippet-library',
    name: 'Shared Snippet Library',
    category: 'helpdesk',
    description: 'Keep the commands, paths and canned replies the team uses, one click from the clipboard.',
    keywords: ['snippet', 'command', 'cheatsheet', 'registry path', 'powershell', 'cmd', 'canned response', 'template', 'clipboard', 'runbook', 'copy paste'],
    icon: 'Library',
    element: () => import('./snippet-library'),
    status: 'stable',
  },
  {
    id: 'speed-test',
    name: 'Speed Test',
    category: 'diagnostics',
    description: 'Rough download, upload and latency check against Cloudflare.',
    keywords: ['bandwidth', 'download', 'upload', 'mbps', 'throughput', 'slow internet', 'latency', 'jitter'],
    icon: 'Gauge',
    element: () => import('./speed-test'),
    status: 'stable',
  },
  {
    id: 'startup-services',
    name: 'Startup and Services Viewer',
    category: 'system',
    description: 'List what starts with this machine and what services are set to run, and flag the odd ones.',
    keywords: ['startup', 'services', 'msconfig', 'autoruns', 'task manager', 'services.msc', 'systemctl', 'launchd', 'launchctl', 'run key', 'slow boot', 'bloat', 'pc is slow', 'malware', 'autostart'],
    icon: 'Rocket',
    element: () => import('./startup-services'),
    status: 'partial',
  },
  {
    id: 'subnet-calculator',
    name: 'Subnet Calculator',
    category: 'network',
    description: 'Turn an IP and mask into network, broadcast, usable range and host count.',
    keywords: ['cidr', 'netmask', 'wildcard', 'broadcast', 'vlsm', 'split', 'prefix', 'ipv6'],
    icon: 'Calculator',
    element: () => import('./subnet-calculator'),
    status: 'stable',
  },
  {
    id: 'subnet-planner',
    name: 'Subnet Planner',
    category: 'network',
    description: 'Carve one network into subnets that fit a list of host counts, and see what is left over.',
    keywords: ['vlsm', 'subnet plan', 'carve', 'allocate', 'address plan', 'ip plan', 'vlan', 'cidr', 'design', 'split network', 'sizing', 'point to point'],
    icon: 'LayoutGrid',
    element: () => import('./subnet-planner'),
    status: 'stable',
  },
  {
    id: 'system-info',
    name: 'System Info Snapshot',
    category: 'system',
    description: "Read this machine's OS, CPU, memory, disks, uptime and serial number in one place.",
    keywords: ['system info', 'msinfo32', 'systeminfo', 'winver', 'uname', 'specs', 'serial number', 'service tag', 'ram', 'cpu', 'disk space', 'uptime', 'model', 'intake'],
    icon: 'Cpu',
    element: () => import('./system-info'),
    status: 'partial',
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    category: 'files',
    description: 'Compare two versions of a config or an export and see exactly which lines changed.',
    keywords: ['diff', 'compare', 'text compare', 'changed lines', 'before and after', 'config', 'ini', 'gpo export', 'switch config', 'winmerge', 'fc', 'patch', 'what changed'],
    icon: 'FileDiff',
    element: () => import('./text-diff'),
    status: 'stable',
  },
  {
    id: 'text-encoder',
    name: 'Text Encoder / Decoder',
    category: 'utilities',
    description: 'Base64, URL, hex and HTML entities both ways, plus a read-only JWT decoder.',
    keywords: ['base64', 'base64url', 'url encode', 'percent encoding', 'hex', 'html entities', 'jwt', 'token', 'decode', 'encode', 'unescape'],
    icon: 'Binary',
    element: () => import('./text-encoder'),
    status: 'stable',
  },
  {
    id: 'ticket-notes',
    name: 'Ticket Note Formatter',
    category: 'helpdesk',
    description: 'Keep timestamped notes while you work, then copy them out in the shape every ticket wants.',
    keywords: ['ticket', 'notes', 'scratchpad', 'timestamp', 'worklog', 'handover', 'issue steps resolution', 'helpdesk', 'servicedesk', 'timesheet', 'paste into ticket'],
    icon: 'NotebookPen',
    element: () => import('./ticket-notes'),
    status: 'stable',
  },
  {
    id: 'tls-prober',
    name: 'TLS Handshake Prober',
    category: 'security',
    description: 'Find out which TLS versions a server will actually accept, and which it refuses.',
    keywords: ['tls', 'ssl', 'handshake', 'tls 1.0', 'tls 1.2', 'cipher', 'protocol', 'openssl', 's_client', 'legacy device'],
    icon: 'Handshake',
    element: () => import('./tls-prober'),
    status: 'stable',
  },
  {
    id: 'totp-generator',
    name: 'TOTP Code Generator',
    category: 'security',
    description: 'Hold the two-factor seeds for shared accounts in an encrypted vault and read the current code.',
    keywords: ['totp', '2fa', 'mfa', 'authenticator', 'otp', 'two factor', 'six digit code', 'google authenticator', 'shared account', 'vault', 'seed', 'otpauth'],
    icon: 'Timer',
    element: () => import('./totp-generator'),
    status: 'stable',
  },
  {
    id: 'traceroute',
    name: 'Traceroute',
    category: 'diagnostics',
    description: 'Follow the path to a host hop by hop and see where it slows down or stops.',
    keywords: ['traceroute', 'tracert', 'tracepath', 'hops', 'path', 'route', 'latency', 'where does it die', 'mtr'],
    icon: 'Route',
    element: () => import('./traceroute'),
    status: 'stable',
  },
  {
    id: 'uptime-ssl-checker',
    name: 'Website / Service Up Checker',
    category: 'diagnostics',
    description: 'Check a URL: HTTP status, redirects, response time and certificate expiry.',
    keywords: ['ssl', 'tls', 'certificate', 'expiry', 'https', 'redirect', 'http status', 'website down', 'uptime', 'cert'],
    icon: 'ShieldCheck',
    element: () => import('./uptime-ssl-checker'),
    status: 'stable',
  },
  {
    id: 'usb-history',
    name: 'USB Device History',
    category: 'system',
    description: 'List the USB devices plugged in now, and on Windows the ones that were plugged in before.',
    keywords: ['usb', 'device manager', 'lsusb', 'usbstor', 'flash drive', 'memory stick', 'what was plugged in', 'driver', 'unknown device', 'peripheral', 'dongle', 'serial number'],
    icon: 'Usb',
    element: () => import('./usb-history'),
    status: 'partial',
  },
  {
    id: 'wake-on-lan',
    name: 'Wake-on-LAN',
    category: 'remote',
    description: 'Wake a machine by MAC address and keep a saved list per site.',
    keywords: ['wol', 'magic packet', 'wake', 'power on', 'remote start', 'etherwake', 'boot'],
    icon: 'Power',
    element: () => import('./wake-on-lan'),
    status: 'stable',
  },
  {
    id: 'warranty-lookup',
    name: 'Warranty / Serial Lookup Helper',
    category: 'helpdesk',
    description: 'Paste a serial number and open the right vendor warranty page, already filled in.',
    keywords: ['warranty', 'serial', 'service tag', 'dell', 'lenovo', 'hp', 'apple', 'coverage', 'support', 'entitlement', 'asset', 'express service code'],
    icon: 'BadgeCheck',
    element: () => import('./warranty-lookup'),
    status: 'stable',
  },
  {
    id: 'wifi-info',
    name: 'Wi-Fi Connection Info',
    category: 'network',
    description: "What this machine's wireless is doing right now: network, band, channel, speed and signal.",
    keywords: ['wifi', 'wireless', 'ssid', 'signal', 'rssi', 'dbm', 'channel', 'band', '2.4ghz', '5ghz', 'netsh wlan', 'iw', 'link speed', 'weak signal', 'roaming', 'bssid', 'access point'],
    icon: 'Wifi',
    element: () => import('./wifi-info'),
    status: 'partial',
  },
  {
    id: 'wifi-qr',
    name: 'Wi-Fi QR Code Generator',
    category: 'utilities',
    description: 'Turn a Wi-Fi network or a link into a QR code guests can scan.',
    keywords: ['qr', 'qr code', 'wifi', 'wi-fi', 'ssid', 'guest network', 'join', 'barcode', 'link', 'url', 'wpa'],
    icon: 'QrCode',
    element: () => import('./wifi-qr'),
    status: 'stable',
  },
]
