// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound method through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).
//
// GenerateQR is the Wi-Fi QR tool's already shipped, already bound method. This
// tool calls it rather than carrying a second QR encoder; it does not touch
// internal/tools/qrgen or app_qrgen.go.

/** Mirrors qrgen.Params in internal/tools/qrgen/qrgen.go. Only text mode is used here. */
export interface QrParams {
  mode: string
  text: string
  ssid: string
  password: string
  security: string
  hidden: boolean
  ecLevel: string
}

/** Mirrors qrgen.Code in internal/tools/qrgen/qrgen.go. */
export interface QrCode {
  size: number
  version: number
  ecLevel: string
  mask: number
  modules: boolean[]
  quiet: number
  payload: string
  payloadBytes: number
  capacity: number
}

interface Bound {
  main?: { App?: { GenerateQR?: (p: QrParams) => Promise<QrCode> } }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/**
 * Null outside the desktop app. A label with no QR code is still a useful
 * label, so this is a background nicety rather than the action the user asked
 * for, and it must not throw.
 */
export async function generateQr(text: string): Promise<QrCode | null> {
  const fn = bound().main?.App?.GenerateQR
  if (!fn) return null
  return fn({
    mode: 'text',
    text,
    ssid: '',
    password: '',
    security: '',
    hidden: false,
    ecLevel: '',
  })
}
