// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound methods through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as shell/bindings.ts).

/** Mirrors certgen.Params in internal/tools/certgen/certgen.go. */
export interface CertParams {
  commonName: string
  sans: string[]
  organization: string
  orgUnit: string
  country: string
  state: string
  locality: string
  email: string
  keyType: string
  days: number
}

/** Mirrors certgen.Result. Every slice is initialised on the Go side, so none
 *  of them arrives as null. */
export interface CertResult {
  privateKeyPem: string
  certificatePem: string
  csrPem: string
  subject: string
  dnsNames: string[]
  ipAddresses: string[]
  keyLabel: string
  notBefore: string
  notAfter: string
  days: number
  serialNumber: string
  fingerprint: string
  suggestedName: string
  warnings: string[]
}

interface Bound {
  main?: {
    App?: {
      GenerateSelfSigned?: (p: CertParams) => Promise<CertResult>
      GenerateCSR?: (p: CertParams) => Promise<CertResult>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function generateSelfSigned(p: CertParams): Promise<CertResult> {
  const fn = bound().main?.App?.GenerateSelfSigned
  if (!fn) throw new Error('Making certificates is only available in the desktop app.')
  return fn(p)
}

export async function generateCsr(p: CertParams): Promise<CertResult> {
  const fn = bound().main?.App?.GenerateCSR
  if (!fn) throw new Error('Making certificates is only available in the desktop app.')
  return fn(p)
}

/** One name per line, blanks dropped, order kept. */
export function splitNames(text: string): string[] {
  return text
    .split(/\r\n|\r|\n/)
    .map((line) => line.trim())
    .filter((line) => line !== '')
}

export type FileKind = 'key' | 'crt' | 'csr'

export function fileNameFor(suggestedName: string, kind: FileKind): string {
  return `${suggestedName}.${kind}`
}
