// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {totp} from '../models';
import {renamer} from '../models';
import {battery} from '../models';
import {wol} from '../models';
import {maildns} from '../models';
import {selfupdate} from '../models';
import {ntpcheck} from '../models';
import {hibp} from '../models';
import {sitecheck} from '../models';
import {dnscmp} from '../models';
import {hashfile} from '../models';
import {dnslook} from '../models';
import {certdec} from '../models';
import {filedrop} from '../models';
import {firewall} from '../models';
import {certgen} from '../models';
import {qrgen} from '../models';
import {main} from '../models';
import {urlcheck} from '../models';
import {swlist} from '../models';
import {lanspeed} from '../models';
import {netinfo} from '../models';
import {netstat} from '../models';
import {ouidb} from '../models';
import {logview} from '../models';
import {tlsprobe} from '../models';
import {pubip} from '../models';
import {rawprint} from '../models';
import {ipscan} from '../models';
import {discover} from '../models';
import {diskscan} from '../models';
import {diskbench} from '../models';
import {dupfind} from '../models';
import {triage} from '../models';
import {pingmon} from '../models';
import {portlisten} from '../models';
import {portscan} from '../models';
import {speedtest} from '../models';
import {tracert} from '../models';
import {startup} from '../models';
import {sysinfo} from '../models';
import {usbhist} from '../models';
import {wifi} from '../models';

export function AddTOTPAccount(arg1:totp.NewAccount):Promise<totp.Account>;

export function ApplyRename(arg1:renamer.Plan):Promise<renamer.ApplyResult>;

export function BatteryHealth():Promise<battery.Report>;

export function CancelJob(arg1:string):Promise<void>;

export function CheckAwake(arg1:string):Promise<wol.Awake>;

export function CheckEmailDNS(arg1:maildns.Params):Promise<maildns.Report>;

export function CheckForUpdate():Promise<selfupdate.Status>;

export function CheckNTPTime(arg1:ntpcheck.Params):Promise<ntpcheck.Report>;

export function CheckPasswordBreach(arg1:string):Promise<hibp.Result>;

export function CheckSite(arg1:sitecheck.Params):Promise<sitecheck.Result>;

export function CompareDNS(arg1:dnscmp.Params):Promise<dnscmp.Comparison>;

export function CompareHash(arg1:string,arg2:hashfile.Digests):Promise<hashfile.Verdict>;

export function CreateTOTPVault(arg1:string):Promise<totp.Status>;

export function DNSCompareServers():Promise<Array<dnscmp.ServerOption>>;

export function DNSServers():Promise<Array<dnslook.ServerOption>>;

export function DecodeCertificateFile(arg1:string):Promise<certdec.Result>;

export function DecodeCertificateText(arg1:string):Promise<certdec.Result>;

export function DiskScanHome():Promise<string>;

export function EmailDKIMSelectors():Promise<Array<string>>;

export function ExportTOTPVault():Promise<string>;

export function FileDropAddresses():Promise<Array<filedrop.Address>>;

export function FileDropSession(arg1:string):Promise<filedrop.Session>;

export function FirewallHint(arg1:number,arg2:string):Promise<firewall.Hint>;

export function GenerateCSR(arg1:certgen.Params):Promise<certgen.Result>;

export function GenerateQR(arg1:qrgen.Params):Promise<qrgen.Code>;

export function GenerateSelfSigned(arg1:certgen.Params):Promise<certgen.Result>;

export function GetAppInfo():Promise<main.AppInfo>;

export function ImportTOTPVault(arg1:string,arg2:string):Promise<totp.ImportReport>;

export function InspectLink(arg1:urlcheck.Params):Promise<urlcheck.Report>;

export function InstalledSoftware():Promise<swlist.Report>;

export function LANSpeedSession(arg1:string):Promise<lanspeed.Session>;

export function ListAdapters():Promise<netinfo.Report>;

export function ListTOTPAccounts():Promise<totp.AccountList>;

export function ListeningPorts():Promise<netstat.Report>;

export function LockTOTPVault():Promise<totp.Status>;

export function LookupMAC(arg1:string):Promise<ouidb.Info>;

export function MACDatabaseInfo():Promise<ouidb.Meta>;

export function OpenLog(arg1:string):Promise<logview.Info>;

export function PickBenchFolder():Promise<string>;

export function PickCertFile():Promise<string>;

export function PickDropFiles():Promise<Array<string>>;

export function PickDropFolder():Promise<string>;

export function PickDuplicateFolder():Promise<string>;

export function PickHashFile():Promise<string>;

export function PickLogFile():Promise<string>;

export function PickRenameFolder():Promise<string>;

export function PickScanFolder():Promise<string>;

export function PreviewRename(arg1:renamer.Params):Promise<renamer.Plan>;

export function ProbeTLS(arg1:tlsprobe.Params):Promise<tlsprobe.Report>;

export function PublicIP():Promise<pubip.Info>;

export function QueryPrinter(arg1:rawprint.Params):Promise<rawprint.Result>;

export function ReadLog(arg1:logview.ReadParams):Promise<logview.Chunk>;

export function RemoveTOTPAccount(arg1:string):Promise<totp.Status>;

export function RestartForUpdate():Promise<boolean>;

export function ScanDefaults():Promise<ipscan.Defaults>;

export function SendPrinterTestPage(arg1:rawprint.Params):Promise<rawprint.Result>;

export function StartDNSLookup(arg1:dnslook.Params):Promise<string>;

export function StartDeviceDiscovery(arg1:discover.Params):Promise<string>;

export function StartDiskScan(arg1:diskscan.Params):Promise<string>;

export function StartDiskSpeed(arg1:diskbench.Params):Promise<string>;

export function StartDuplicateScan(arg1:dupfind.Params):Promise<string>;

export function StartFileDrop(arg1:filedrop.Params):Promise<string>;

export function StartFileHash(arg1:hashfile.Params):Promise<string>;

export function StartIPScan(arg1:ipscan.ScanParams):Promise<string>;

export function StartInstallUpdate():Promise<string>;

export function StartInternetTriage(arg1:triage.Params):Promise<string>;

export function StartLANSpeed(arg1:lanspeed.Params):Promise<string>;

export function StartLogSearch(arg1:logview.SearchParams):Promise<string>;

export function StartPingMonitor(arg1:pingmon.Params):Promise<string>;

export function StartPortListener(arg1:portlisten.Params):Promise<string>;

export function StartPortScan(arg1:portscan.Params):Promise<string>;

export function StartSpeedTest(arg1:speedtest.Params):Promise<string>;

export function StartTraceroute(arg1:tracert.Params):Promise<string>;

export function StartupItems():Promise<startup.Report>;

export function SystemInfo():Promise<sysinfo.Report>;

export function TOTPCodes():Promise<totp.CodeSet>;

export function TOTPStatus():Promise<totp.Status>;

export function USBDevices():Promise<usbhist.Report>;

export function UndoRename(arg1:renamer.Batch):Promise<renamer.ApplyResult>;

export function UnlockTOTPVault(arg1:string):Promise<totp.Status>;

export function WakeDevice(arg1:wol.WakeParams):Promise<wol.WakeResult>;

export function WakeTargets():Promise<wol.TargetList>;

export function WiFiInfo():Promise<wifi.Report>;
