// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTOTPAccount(arg1) {
  return window['go']['main']['App']['AddTOTPAccount'](arg1);
}

export function ApplyRename(arg1) {
  return window['go']['main']['App']['ApplyRename'](arg1);
}

export function BatteryHealth() {
  return window['go']['main']['App']['BatteryHealth']();
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function CheckAwake(arg1) {
  return window['go']['main']['App']['CheckAwake'](arg1);
}

export function CheckEmailDNS(arg1) {
  return window['go']['main']['App']['CheckEmailDNS'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckNTPTime(arg1) {
  return window['go']['main']['App']['CheckNTPTime'](arg1);
}

export function CheckPasswordBreach(arg1) {
  return window['go']['main']['App']['CheckPasswordBreach'](arg1);
}

export function CheckSite(arg1) {
  return window['go']['main']['App']['CheckSite'](arg1);
}

export function CompareDNS(arg1) {
  return window['go']['main']['App']['CompareDNS'](arg1);
}

export function CompareHash(arg1, arg2) {
  return window['go']['main']['App']['CompareHash'](arg1, arg2);
}

export function CreateTOTPVault(arg1) {
  return window['go']['main']['App']['CreateTOTPVault'](arg1);
}

export function DNSCompareServers() {
  return window['go']['main']['App']['DNSCompareServers']();
}

export function DNSServers() {
  return window['go']['main']['App']['DNSServers']();
}

export function DecodeCertificateFile(arg1) {
  return window['go']['main']['App']['DecodeCertificateFile'](arg1);
}

export function DecodeCertificateText(arg1) {
  return window['go']['main']['App']['DecodeCertificateText'](arg1);
}

export function DiskScanHome() {
  return window['go']['main']['App']['DiskScanHome']();
}

export function EmailDKIMSelectors() {
  return window['go']['main']['App']['EmailDKIMSelectors']();
}

export function ExportTOTPVault() {
  return window['go']['main']['App']['ExportTOTPVault']();
}

export function FileDropAddresses() {
  return window['go']['main']['App']['FileDropAddresses']();
}

export function FileDropSession(arg1) {
  return window['go']['main']['App']['FileDropSession'](arg1);
}

export function GenerateCSR(arg1) {
  return window['go']['main']['App']['GenerateCSR'](arg1);
}

export function GenerateQR(arg1) {
  return window['go']['main']['App']['GenerateQR'](arg1);
}

export function GenerateSelfSigned(arg1) {
  return window['go']['main']['App']['GenerateSelfSigned'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function ImportTOTPVault(arg1, arg2) {
  return window['go']['main']['App']['ImportTOTPVault'](arg1, arg2);
}

export function InspectLink(arg1) {
  return window['go']['main']['App']['InspectLink'](arg1);
}

export function InstalledSoftware() {
  return window['go']['main']['App']['InstalledSoftware']();
}

export function LANSpeedSession(arg1) {
  return window['go']['main']['App']['LANSpeedSession'](arg1);
}

export function ListAdapters() {
  return window['go']['main']['App']['ListAdapters']();
}

export function ListTOTPAccounts() {
  return window['go']['main']['App']['ListTOTPAccounts']();
}

export function ListeningPorts() {
  return window['go']['main']['App']['ListeningPorts']();
}

export function LockTOTPVault() {
  return window['go']['main']['App']['LockTOTPVault']();
}

export function LookupMAC(arg1) {
  return window['go']['main']['App']['LookupMAC'](arg1);
}

export function MACDatabaseInfo() {
  return window['go']['main']['App']['MACDatabaseInfo']();
}

export function OpenLog(arg1) {
  return window['go']['main']['App']['OpenLog'](arg1);
}

export function PickBenchFolder() {
  return window['go']['main']['App']['PickBenchFolder']();
}

export function PickCertFile() {
  return window['go']['main']['App']['PickCertFile']();
}

export function PickDropFiles() {
  return window['go']['main']['App']['PickDropFiles']();
}

export function PickDropFolder() {
  return window['go']['main']['App']['PickDropFolder']();
}

export function PickDuplicateFolder() {
  return window['go']['main']['App']['PickDuplicateFolder']();
}

export function PickHashFile() {
  return window['go']['main']['App']['PickHashFile']();
}

export function PickLogFile() {
  return window['go']['main']['App']['PickLogFile']();
}

export function PickRenameFolder() {
  return window['go']['main']['App']['PickRenameFolder']();
}

export function PickScanFolder() {
  return window['go']['main']['App']['PickScanFolder']();
}

export function PreviewRename(arg1) {
  return window['go']['main']['App']['PreviewRename'](arg1);
}

export function ProbeTLS(arg1) {
  return window['go']['main']['App']['ProbeTLS'](arg1);
}

export function PublicIP() {
  return window['go']['main']['App']['PublicIP']();
}

export function QueryPrinter(arg1) {
  return window['go']['main']['App']['QueryPrinter'](arg1);
}

export function ReadLog(arg1) {
  return window['go']['main']['App']['ReadLog'](arg1);
}

export function RemoveTOTPAccount(arg1) {
  return window['go']['main']['App']['RemoveTOTPAccount'](arg1);
}

export function ScanDefaults() {
  return window['go']['main']['App']['ScanDefaults']();
}

export function SendPrinterTestPage(arg1) {
  return window['go']['main']['App']['SendPrinterTestPage'](arg1);
}

export function StartDNSLookup(arg1) {
  return window['go']['main']['App']['StartDNSLookup'](arg1);
}

export function StartDeviceDiscovery(arg1) {
  return window['go']['main']['App']['StartDeviceDiscovery'](arg1);
}

export function StartDiskScan(arg1) {
  return window['go']['main']['App']['StartDiskScan'](arg1);
}

export function StartDiskSpeed(arg1) {
  return window['go']['main']['App']['StartDiskSpeed'](arg1);
}

export function StartDuplicateScan(arg1) {
  return window['go']['main']['App']['StartDuplicateScan'](arg1);
}

export function StartFileDrop(arg1) {
  return window['go']['main']['App']['StartFileDrop'](arg1);
}

export function StartFileHash(arg1) {
  return window['go']['main']['App']['StartFileHash'](arg1);
}

export function StartIPScan(arg1) {
  return window['go']['main']['App']['StartIPScan'](arg1);
}

export function StartInternetTriage(arg1) {
  return window['go']['main']['App']['StartInternetTriage'](arg1);
}

export function StartLANSpeed(arg1) {
  return window['go']['main']['App']['StartLANSpeed'](arg1);
}

export function StartLogSearch(arg1) {
  return window['go']['main']['App']['StartLogSearch'](arg1);
}

export function StartPingMonitor(arg1) {
  return window['go']['main']['App']['StartPingMonitor'](arg1);
}

export function StartPortListener(arg1) {
  return window['go']['main']['App']['StartPortListener'](arg1);
}

export function StartPortScan(arg1) {
  return window['go']['main']['App']['StartPortScan'](arg1);
}

export function StartSpeedTest(arg1) {
  return window['go']['main']['App']['StartSpeedTest'](arg1);
}

export function StartTraceroute(arg1) {
  return window['go']['main']['App']['StartTraceroute'](arg1);
}

export function StartupItems() {
  return window['go']['main']['App']['StartupItems']();
}

export function SystemInfo() {
  return window['go']['main']['App']['SystemInfo']();
}

export function TOTPCodes() {
  return window['go']['main']['App']['TOTPCodes']();
}

export function TOTPStatus() {
  return window['go']['main']['App']['TOTPStatus']();
}

export function USBDevices() {
  return window['go']['main']['App']['USBDevices']();
}

export function UndoRename(arg1) {
  return window['go']['main']['App']['UndoRename'](arg1);
}

export function UnlockTOTPVault(arg1) {
  return window['go']['main']['App']['UnlockTOTPVault'](arg1);
}

export function WakeDevice(arg1) {
  return window['go']['main']['App']['WakeDevice'](arg1);
}

export function WakeTargets() {
  return window['go']['main']['App']['WakeTargets']();
}

export function WiFiInfo() {
  return window['go']['main']['App']['WiFiInfo']();
}
