// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dir():Promise<string>;

export function Get(arg1:string):Promise<string>;

export function List():Promise<Array<string>>;

export function Portable():Promise<boolean>;

export function Set(arg1:string,arg2:string):Promise<void>;
