// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dir() {
  return window['go']['store']['Store']['Dir']();
}

export function Get(arg1) {
  return window['go']['store']['Store']['Get'](arg1);
}

export function List() {
  return window['go']['store']['Store']['List']();
}

export function Portable() {
  return window['go']['store']['Store']['Portable']();
}

export function Set(arg1, arg2) {
  return window['go']['store']['Store']['Set'](arg1, arg2);
}
