// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors lanspeed.Params in internal/tools/lanspeed/lanspeed.go. */
export interface SpeedParams {
  port: number
  sizeMb: number
}

/** Mirrors lanspeed.Session. Empty when the job is not a running test. */
export interface Session {
  token: string
  port: number
  url: string
  sizeMb: number
}

/** Mirrors lanspeed.Pull. */
export interface Pull {
  time: string
  peer: string
  bytes: number
  seconds: number
  mbps: number
  /** "ok" when the whole stream went out, "stopped" when they hung up. */
  status: string
  reading: string
}

/** Mirrors filedrop.Address in internal/tools/filedrop/filedrop.go. */
export interface Address {
  ip: string
  adapter: string
  primary: boolean
}

interface Bound {
  main?: {
    App?: {
      StartLANSpeed?: (p: SpeedParams) => Promise<string>
      LANSpeedSession?: (jobId: string) => Promise<Session>
      // Already shipped and already bound by LAN File Drop. Owning no address
      // enumerator means writing no second one, not refusing to call the one
      // that is there. This tool does not touch internal/tools/filedrop or
      // app_filedrop.go.
      FileDropAddresses?: () => Promise<Address[] | null>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Pulls arrive as "pull" items on job:result. */
export async function startLanSpeed(p: SpeedParams): Promise<string> {
  const fn = bound().main?.App?.StartLANSpeed
  if (!fn) throw new Error('The LAN throughput test is only available in the desktop app.')
  return fn(p)
}

/** The link a running test is serving. Null outside the desktop app. */
export async function lanSpeedSession(jobId: string): Promise<Session | null> {
  const fn = bound().main?.App?.LANSpeedSession
  if (!fn) return null
  return fn(jobId)
}

/** Empty outside the desktop app: the page still renders, it just offers no address. */
export async function speedAddresses(): Promise<Address[]> {
  const fn = bound().main?.App?.FileDropAddresses
  if (!fn) return []
  return (await fn()) ?? []
}
