// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound methods through the runtime global instead of
// importing a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors lanspeed.Params in internal/tools/lanspeed/lanspeed.go. */
export interface SpeedParams {
  port: number
  sizeMb: number
}

/** Mirrors lanspeed.Session. Empty when the job is not a running test. */
export interface Session {
  token: string
  port: number
  url: string
  sizeMb: number
}

/** Mirrors lanspeed.Pull. */
export interface Pull {
  time: string
  peer: string
  bytes: number
  seconds: number
  mbps: number
  /** "ok" when the whole stream went out, "stopped" when they hung up. */
  status: string
  reading: string
}

/** Mirrors filedrop.Address in internal/tools/filedrop/filedrop.go. */
export interface Address {
  ip: string
  adapter: string
  primary: boolean
}

interface Bound {
  main?: {
    App?: {
      StartLANSpeed?: (p: SpeedParams) => Promise<string>
      LANSpeedSession?: (jobId: string) => Promise<Session>
      // Already shipped and already bound by LAN File Drop. Owning no address
      // enumerator means writing no second one, not refusing to call the one
      // that is there. This tool does not touch internal/tools/filedrop or
      // app_filedrop.go.
      FileDropAddresses?: () => Promise<Address[] | null>
      // Already shipped and already bound by the Wi-Fi QR tool, and called the
      // same way by label-maker and lan-file-drop. This tool does not touch
      // internal/tools/qrgen or app_qrgen.go.
      GenerateQR?: (p: QrParams) => Promise<QrCode>
      FirewallHint?: (port: number, proto: string) => Promise<FirewallHint>
    }
  }
}

/** Mirrors qrgen.Params in internal/tools/qrgen/qrgen.go. Only text mode is used here. */
export interface QrParams {
  mode: string
  text: string
  ssid: string
  password: string
  security: string
  hidden: boolean
  ecLevel: string
}

/** Mirrors qrgen.Code in internal/tools/qrgen/qrgen.go. */
export interface QrCode {
  size: number
  version: number
  ecLevel: string
  mask: number
  modules: boolean[]
  quiet: number
  payload: string
  payloadBytes: number
  capacity: number
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

/** Resolves to the job id. Pulls arrive as "pull" items on job:result. */
export async function startLanSpeed(p: SpeedParams): Promise<string> {
  const fn = bound().main?.App?.StartLANSpeed
  if (!fn) throw new Error('The LAN throughput test is only available in the desktop app.')
  return fn(p)
}

/** The link a running test is serving. Null outside the desktop app. */
export async function lanSpeedSession(jobId: string): Promise<Session | null> {
  const fn = bound().main?.App?.LANSpeedSession
  if (!fn) return null
  return fn(jobId)
}

/** Empty outside the desktop app: the page still renders, it just offers no address. */
export async function speedAddresses(): Promise<Address[]> {
  const fn = bound().main?.App?.FileDropAddresses
  if (!fn) return []
  return (await fn()) ?? []
}

/**
 * The QR module matrix for the test link. Null outside the desktop app, and
 * null rather than a throw if the encoder refuses: the link is readable as text
 * beside it either way, so a missing code must never take the page down.
 */
export async function generateQr(text: string): Promise<QrCode | null> {
  const fn = bound().main?.App?.GenerateQR
  if (!fn) return null
  try {
    return await fn({
      mode: 'text',
      text,
      ssid: '',
      password: '',
      security: '',
      hidden: false,
      ecLevel: '',
    })
  } catch {
    return null
  }
}

/** Mirrors firewall.Hint in internal/firewall/firewall.go. Every field is empty
 *  when nothing was detected, which the page renders as nothing at all. */
export interface FirewallHint {
  firewall: string
  message: string
  command: string
}

/**
 * Whether a firewall on this computer might be dropping the connections the
 * other machine is making. A dropped packet produces no error at either end, so
 * without this the page cannot tell "blocked" from "nobody has tried yet".
 * Empty outside the desktop app, and it must never throw: this is a hint beside
 * a working share, not the thing the user asked for.
 */
export async function firewallHint(port: number, proto: string): Promise<FirewallHint | null> {
  const fn = bound().main?.App?.FirewallHint
  if (!fn) return null
  try {
    return await fn(port, proto)
  } catch {
    return null
  }
}
