// The files under frontend/wailsjs are generated by "wails build", so this tool
// reaches its bound method through the runtime global instead of importing a
// file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors sitecheck.Params in internal/tools/sitecheck/sitecheck.go. */
export interface SiteParams {
  url: string
  timeoutMs: number
  followRedirects: boolean
}

/** Mirrors sitecheck.Hop. */
export interface Hop {
  url: string
  status: number
  location: string
}

/** Mirrors sitecheck.Timing. */
export interface Timing {
  dnsMs: number
  connectMs: number
  tlsMs: number
  ttfbMs: number
  totalMs: number
}

/** Mirrors sitecheck.TLSInfo in internal/tools/sitecheck/cert.go. */
export interface TlsInfo {
  version: string
  cipherSuite: string
  subject: string
  commonName: string
  issuer: string
  sans: string[] | null
  notBefore: string
  notAfter: string
  daysRemaining: number
  expired: boolean
  notYetValid: boolean
  hostnameMatch: boolean
  chainValid: boolean
  chainError: string
  selfSigned: boolean
  chainSubjects: string[] | null
  serialNumber: string
  signatureAlgorithm: string
  keyType: string
  sha256Fingerprint: string
}

/** Mirrors sitecheck.Result. */
export interface SiteResult {
  url: string
  finalUrl: string
  status: number
  statusText: string
  /** "ok", "warn" or "error". */
  level: string
  headline: string
  ip: string
  serverHeader: string
  bodyBytes: number
  redirects: Hop[] | null
  timing: Timing
  tls: TlsInfo | null
  warnings: string[] | null
  errors: string[] | null
  checkedAt: string
}

interface Bound {
  main?: {
    App?: {
      CheckSite?: (params: SiteParams) => Promise<SiteResult>
    }
  }
}

function bound(): Bound {
  return (window as unknown as { go?: Bound }).go ?? {}
}

export async function checkSite(params: SiteParams): Promise<SiteResult> {
  const fn = bound().main?.App?.CheckSite
  if (!fn) throw new Error('Checking a site only works inside the CHIT desktop app.')
  return fn(params)
}
