// The files under frontend/wailsjs are generated by "wails build", so this
// tool reaches its bound method through the runtime global instead of importing
// a file that may not have been regenerated yet (same approach as
// src/shell/bindings.ts).

/** Mirrors startup.Item in internal/tools/startup/startup.go. */
export interface Item {
  name: string
  /** "startup" or "service". */
  kind: string
  source: string
  command: string
  publisher: string
  /** "automatic", "manual", "disabled", "boot", or "" when this OS did not say. */
  startMode: string
  /** "running", "stopped", or "" when this OS did not say. */
  state: string
  enabled: boolean
  /** A full sentence when the entry is worth a second look, otherwise empty. */
  concern: string
}

/** Mirrors startup.Report. */
export interface Report {
  os: string
  items: Item[] | null
  unsupported: string[] | null
  note: string
}

interface Bound {
  main?: {
    App?: {
      StartupItems?: () => Promise<Report>
    }
  }
}

export async function startupItems(): Promise<Report> {
  const fn = (window as unknown as { go?: Bound }).go?.main?.App?.StartupItems
  if (!fn) {
    throw new Error('Startup entries are only available in the desktop app.')
  }
  return fn()
}
